/* Original procedural score by Codex for Jack's game. Music is procedural; Skull Screecher uses a licensed CC0 recording (assets/audio/CREDITS.md). */
(function(){
const skullScreamUrl=new URL('assets/audio/skull-scream.wav',document.currentScript.src).href;
class Soundtrack {
 constructor(){this.ctx=null;this.volume=.45;this.scene='menu';this.step=0;this.next=0;this.last={};this.running=false;}
 start(){if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=this.volume*.45;this.background=this.ctx.createGain();this.background.gain.value=1;this.background.connect(this.master);const compressor=this.ctx.createDynamicsCompressor();this.master.connect(compressor);compressor.connect(this.ctx.destination);this.delay=this.ctx.createDelay(1);this.delay.delayTime.value=.31;const feedback=this.ctx.createGain();feedback.gain.value=.22;const wet=this.ctx.createGain();wet.gain.value=.13;this.delay.connect(feedback);feedback.connect(this.delay);this.delay.connect(wet);wet.connect(this.background);this.next=this.ctx.currentTime+.08;this.running=true;this.timer=setInterval(()=>this.schedule(),100);}this.ctx.resume().catch(()=>{});this.loadSkullScream();}
 setVolume(v){this.volume=v;if(this.master)this.master.gain.setTargetAtTime(v*.45,this.ctx.currentTime,.06);}
 setScene(scene){if(this.scene===scene)return;this.scene=scene;this.step=0;if(this.ctx)this.next=this.ctx.currentTime+.08;}
 note(midi,t,duration,volume=.08,type='triangle',echo=false){if(!this.ctx)return;const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type=type;osc.frequency.value=440*Math.pow(2,(midi-69)/12);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(volume,t+.015);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);osc.connect(gain);gain.connect(this.background);if(echo)gain.connect(this.delay);osc.start(t);osc.stop(t+duration+.03);}
 noise(t,duration,volume,cutoff=1200){const size=Math.ceil(this.ctx.sampleRate*duration),buffer=this.ctx.createBuffer(1,size,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<size;i++)data[i]=(Math.random()*2-1)*(1-i/size);const src=this.ctx.createBufferSource();src.buffer=buffer;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=cutoff;const gain=this.ctx.createGain();gain.gain.setValueAtTime(volume,t);gain.gain.exponentialRampToValueAtTime(.0001,t+duration);src.connect(filter);filter.connect(gain);gain.connect(this.background);src.start(t);}
 schedule(){if(!this.ctx||this.ctx.state!=='running')return;if(this.next<this.ctx.currentTime-.5)this.next=this.ctx.currentTime+.03;const themes={menu:{tempo:76,roots:[45,41,48,43],melody:[69,72,76,74,72,69,67,64,65,69,72,71,69,65,64,62]},battle:{tempo:104,roots:[45,45,41,43],melody:[69,76,72,76,71,74,72,69,65,72,69,72,67,74,71,67]},boss:{tempo:126,roots:[38,39,38,45],melody:[62,69,65,63,62,65,69,70,63,70,67,65,62,61,65,69]},victory:{tempo:90,roots:[48,43,45,41],melody:[72,76,79,76,74,79,77,74,76,81,79,76,77,76,74,72]}};const th=themes[this.scene]||themes.menu,beat=60/th.tempo/2;while(this.next<this.ctx.currentTime+.25){const t=this.next,s=this.step,root=th.roots[Math.floor(s/8)%4];if(s%8===0){for(const n of [root+12,root+19,root+24])this.note(n,t,beat*9,.034,'sine',true);this.note(root,t,beat*7,.12,'triangle');}const melody=th.melody[s%th.melody.length];if(this.scene==='menu'){if(s%2===0)this.note(melody,t,beat*2.5,.085,'sine',true);this.note(root+[12,19,24,19][s%4],t,beat*1.8,.04,'triangle',true);}else{this.note(melody,t,beat*1.3,.075,'triangle',true);if(s%2===0){this.note(31,t,.16,.15,'sine');this.noise(t,.065,.025,650);}if(s%4===2)this.noise(t,.1,.05,2000);if(this.scene==='boss'){this.note(root+12+(s%2?7:0),t,.13,.04,'sawtooth');this.noise(t,.03,.025,4500);}}this.step++;this.next+=beat;}}
 loadSkullScream(){if(!this.ctx)return Promise.resolve(null);if(!this.skullScreamLoading)this.skullScreamLoading=fetch(skullScreamUrl).then(r=>{if(!r.ok)throw Error('Scream audio unavailable');return r.arrayBuffer();}).then(data=>this.ctx.decodeAudioData(data)).then(buffer=>this.skullScreamBuffer=buffer).catch(()=>{this.skullScreamLoading=null;return null;});return this.skullScreamLoading;}
 recordedSkullScream(){if(!this.ctx||this.volume<=0)return;if(!this.skullScreamBuffer){this.loadSkullScream().then(buffer=>{if(buffer)this.recordedSkullScream();});return;}const c=this.ctx,t=c.currentTime,out=c.createGain();
 // Blend a rasping descending shriek with a low creature throat, using the recorded voice.
 // The screech stays prominent while the other sounds briefly duck.
 out.gain.setValueAtTime(0,t);out.gain.linearRampToValueAtTime(.55,t+.025);out.gain.setValueAtTime(.50,t+.95);out.gain.linearRampToValueAtTime(0,t+1.4);out.connect(this.master);const duck=this.background.gain;duck.cancelAndHoldAtTime(t);duck.linearRampToValueAtTime(.25,t+.025);duck.setValueAtTime(.25,t+1.4);duck.linearRampToValueAtTime(1,t+1.65);let remaining=2;
 for(const low of [false,true]){const src=c.createBufferSource(),filter=c.createBiquadFilter(),mix=c.createGain();src.buffer=this.skullScreamBuffer;src.playbackRate.setValueAtTime(low?.64:1.24,t);src.playbackRate.exponentialRampToValueAtTime(low?.57:.92,t+1.35);filter.type=low?'lowpass':'highpass';filter.frequency.value=low?950:240;filter.Q.value=.7;mix.gain.value=low?.35:.65;src.connect(filter);filter.connect(mix);mix.connect(out);src.start(t);src.stop(t+1.4);src.onended=()=>{src.disconnect();filter.disconnect();mix.disconnect();if(--remaining===0)out.disconnect();};}this.lastRecordedSkullScream=t;}

 scream(t,quiet=false){const c=this.ctx,voice=c.createOscillator(),vibrato=c.createOscillator(),depth=c.createGain(),filter=c.createBiquadFilter(),gain=c.createGain();voice.type='sawtooth';voice.frequency.setValueAtTime(240,t);voice.frequency.exponentialRampToValueAtTime(640,t+.14);voice.frequency.exponentialRampToValueAtTime(310,t+.95);vibrato.frequency.value=29;depth.gain.value=35;vibrato.connect(depth);depth.connect(voice.frequency);filter.type='bandpass';filter.frequency.setValueAtTime(1100,t);filter.frequency.linearRampToValueAtTime(1800,t+.25);filter.frequency.linearRampToValueAtTime(800,t+.95);filter.Q.value=2;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(quiet?.055:.12,t+.06);gain.gain.setValueAtTime(quiet?.045:.1,t+.65);gain.gain.exponentialRampToValueAtTime(.0001,t+1);voice.connect(filter);filter.connect(gain);gain.connect(this.background);voice.start(t);vibrato.start(t);voice.stop(t+1.02);vibrato.stop(t+1.02);voice.onended=()=>{voice.disconnect();vibrato.disconnect();depth.disconnect();filter.disconnect();gain.disconnect();};this.noise(t,.9,quiet?.015:.045,quiet?1700:3200);}
 effect(name){if(!this.ctx||this.volume<=0)return;const t=this.ctx.currentTime;if(t-(this.last[name]||-100)<({attack:.12,kill:.13,explosion:.15}[name]||.06))return;this.last[name]=t;if(name==='skullScream'){this.recordedSkullScream();return;}if(name==='zombieScream'){this.scream(t);return;}if(name==='knight'||name==='rogue'){this.noise(t,.07,.06,2400);this.note(77,t,.065,.025,'triangle');}else if(name==='archer'){this.noise(t,.055,.045,4800);this.note(83,t,.06,.022,'sine');}else if(name==='serpent'){this.noise(t,.12,.035,700);this.note(72,t,.15,.025,'sine',true);}else if(name==='mage'){this.note(79,t,.18,.055,'sine',true);this.note(86,t+.025,.13,.03,'triangle');}else if(name==='buy'||name==='upgrade'||name==='sell'||name==='tree'){[67,72,76].forEach((n,i)=>this.note(n,t+i*.07,.23,.09,'triangle',true));}else if(name==='wave'){[45,52,57].forEach((n,i)=>this.note(n,t+i*.14,.5,.13,'triangle'));}else if(name==='complete'||name==='win'){[60,64,67,72,76].forEach((n,i)=>this.note(n,t+i*.12,.65,.12,'triangle',true));}else if(name==='lose'){[57,53,50,45].forEach((n,i)=>this.note(n,t+i*.25,.8,.12,'triangle'));}else if(name==='leak'){this.note(42,t,.4,.13,'sawtooth');this.note(41,t+.1,.3,.06,'triangle');}else if(name==='ability'){[57,64,69,76,81].forEach((n,i)=>this.note(n,t+i*.045,.45,.09,'triangle',true));this.noise(t,.5,.09,1100);}else if(name==='explosion'){this.noise(t,.25,.12,650);this.note(28,t,.2,.15,'sine');}else if(name==='fear'){this.note(45,t,.45,.07,'sawtooth');this.note(52,t,.4,.06,'triangle');}else if(name==='click')this.note(76,t,.08,.055,'sine');}
}
window.Soundtrack=Soundtrack;
})();
