function showVillageDiary(){
 menuScreen='diary';menu=true;paused=true;
 const book=read(VillageDiary.key,{}),types=Object.keys(D.enemies).sort((a,b)=>D.enemies[a].wave-D.enemies[b].wave);
 const escape=text=>{const n=document.createElement('span');n.textContent=text;return n.innerHTML;};
 const statRows=d=>{const labels={hp:'Base health',loss:'Villagers lost on escape',reward:'Gold reward',wave:'First round',armor:'Armor per hit',blocks:'Effects blocked',fearReduction:'Fear duration reduction',boss:'Boss',camouflage:'Camouflage',ironHardness:'Iron Hardness',energyShield:'Energy Shield',immuneDamage:'Damage immunities',immuneEffects:'Effect immunities',onlyDamage:'Only takes damage from',damageTaken:'Damage multipliers'};return Object.entries(d).filter(([k])=>!['name','hint','color','time'].includes(k)).map(([k,v])=>'<dt>'+escape(labels[k]||k)+'</dt><dd>'+escape(k==='fearReduction'?Math.round(v*100)+'%':typeof v==='boolean'?(v?'Yes':'No'):Array.isArray(v)?v.join(', '):typeof v==='object'?Object.entries(v).map(([a,b])=>a+': '+b+'×').join(', '):v)+'</dd>').join('')+'<dt>Speed relative to Skeleton</dt><dd>'+Number((D.enemies.skeleton.time/d.time).toFixed(3))+'×</dd><dt>Base route travel time</dt><dd>'+Number(d.time.toFixed(3))+' seconds</dd>';};
 modal('<h2>Village Diary</h2><p>Defeat monsters to discover them. Description at 40 defeats · Stats at 100 · Lore at 200.</p><div class="buttons">'+button('Back to Main Menu','diary-back','ghost')+'</div><div class="diary-list">'+types.map(type=>{const e=VillageDiary.entry(book,type),d=D.enemies[type];if(!e.unlocked)return '<article class="diary-entry diary-locked"><div class="diary-lock" aria-hidden="true">?</div><h3>Locked</h3><p>Defeat this monster to reveal it.</p></article>';return '<article class="diary-entry"><canvas width="320" height="260" data-diary="'+type+'" aria-label="'+escape(d.name)+'"></canvas><div><h3>'+escape(d.name)+'</h3><small>'+e.kills+' defeated'+(type==='tiny'?' (each count = 10 Tiny Skeleton kills)':'')+(e.next?' · Next discovery at '+e.next:' · Fully discovered')+'</small>'+(e.description?'<p>'+escape(e.description)+'</p>':'<p>Description locked</p>')+(e.stats?'<details><summary>All stats</summary><p>Base values; round health scaling and enemy abilities can change them during play.</p><dl>'+statRows(d)+'</dl><p>'+escape(d.hint)+'</p></details>':'<p>Stats locked</p>')+(e.lore?'<aside><h4>Lore</h4><p>'+escape(e.lore)+'</p></aside>':'<p>Lore locked</p>')+'</div></article>';}).join('')+'</div>','diary-card');
 $('diary-back').onclick=showMenu;const container=$('modal').querySelector('.diary-card'),sample=new E.Game(),portraits=[...container.querySelectorAll('canvas')].map(canvas=>({c:canvas.getContext('2d'),e:sample.spawn(canvas.dataset.diary,false,300)}));
 function draw(now){if(!container.isConnected)return;const time=matchMedia('(prefers-reduced-motion: reduce)').matches?1:now/1000;for(const {c,e}of portraits){c.clearRect(0,0,320,260);c.save();const type=e.type,scale=type==='nightmare'?1.3:type==='dragon'?1:type==='giant'?1.3:type==='werewolf'?1.2:type==='fusion'?1.6:type==='ironball'?1.7:2;c.translate(160,type==='nightmare'?238:190);c.scale(scale,scale);const sprite={...e,x:0,y:0,p:300+time*30,born:time};if(type==='nightmare')NightmareArt.draw(c,sprite,time,sample.nightmareFlight(e));else CartoonArt.enemy(c,sprite,time);c.restore();}requestAnimationFrame(draw);}requestAnimationFrame(draw);
}
