/* Paused, read-only upgrade catalogue. Uses the live hero data and descriptions. */
let upgradeViewer=null;
const upgradeThemes={
 knight:[['⚔','Heavy strikes','#e8a04a'],['✦','Fast combos','#56c9ac'],['⛨','Defense & control','#7bb4ee'],['☀','Holy fire','#dd87bb']],
 archer:[['➶','Piercing power','#e8a04a'],['➹','Rapid volleys','#56c9ac'],['ϟ','Elemental effects','#7bb4ee'],['◎','Range & precision','#dd87bb']],
 mage:[['♨','Fire & explosions','#ee975e'],['❄','Ice & control','#79cbea'],['ϟ','Chain lightning','#dec26c'],['✧','Arcane beams','#bf99ed']],
 rogue:[['†','Single-target damage','#ec9281'],['☠','Poison & spreading damage','#9ecf70'],['⌘','Traps & disruption','#7dbde3'],['◈','Gold & bounties','#e5c269']],
 leader:[['⚑','Damage & attack speed','#ea9a70'],['♜','Fear & control','#c399e0'],['◉','Range & cooldowns','#7bbce7'],['◈','Village & economy','#a9cb75']]
};
function openUpgradeViewer(id){const h=game.s.heroes.find(h=>h.id===id);if(!h||menu||upgradeViewer)return;upgradeViewer={id,path:0,tier:Math.min(h.u[0],5),wasPaused:paused,focus:document.activeElement};aiming=null;renderUpgradeViewer();}
function closeUpgradeViewer(){if(!upgradeViewer)return;const previous=upgradeViewer;upgradeViewer=null;$('modal').classList.add('hidden');paused=previous.wasPaused;updateUi(true);if(previous.focus?.isConnected)previous.focus.focus();else $('view-upgrades')?.focus();}
function renderUpgradeViewer(){const h=game.s.heroes.find(h=>h.id===upgradeViewer.id);if(!h)return closeUpgradeViewer();const hero=D.heroes[h.type],themes=upgradeThemes[h.type];
 modal(`<section class="upgrade-library"><header class="library-header"><div><span class="library-kicker">HERO UPGRADES · GAME PAUSED</span><h2>${hero.name}</h2><p>Explore your build. Select any upgrade to see what it does.</p></div><button id="close-upgrades" class="library-close">← Back to game</button></header><div class="library-layout"><div class="library-paths">${hero.paths.map((p,i)=>{const theme=themes[i];return `<section class="library-path" style="--path-color:${theme[2]}" aria-label="${p.name}"><header><span class="path-emblem">${theme[0]}</span><div><h3>${p.name}</h3><span>${theme[1]}</span></div><small>${h.u[i]} / 6</small></header><div class="upgrade-track">${p.names.map((name,n)=>{const owned=n<h.u[i],state=game.upgradeState(h,i),next=n===h.u[i]&&!state.locked;return `<button class="upgrade-tile ${owned?'owned':''} ${i===upgradeViewer.path&&n===upgradeViewer.tier?'chosen':''}" data-inspect-path="${i}" data-inspect-tier="${n}" aria-pressed="${i===upgradeViewer.path&&n===upgradeViewer.tier}"><span class="tile-tier">TIER ${n+1}</span><span class="tile-icon">${n===5?'♛':theme[0]}</span><strong>${name}</strong><small>${owned?'✓ Purchased':next?'Next upgrade':state.locked?'Locked · inspect':n===5?'Ability tier':'Future upgrade'}</small></button>`;}).join('')}</div></section>`;}).join('')}<p class="library-rule">Choose 2 paths. One can reach tier 6; the other stops at tier 2. Tier limits apply to heroes of the same class and path: 3 at tier 4, 2 at tier 5, 1 at tier 6.</p></div><aside class="library-detail" id="library-detail" aria-live="polite"></aside></div></section>`,'upgrade-library-card');
 $('close-upgrades').onclick=closeUpgradeViewer;document.querySelectorAll('[data-inspect-path]').forEach(b=>b.onclick=()=>{upgradeViewer.path=+b.dataset.inspectPath;upgradeViewer.tier=+b.dataset.inspectTier;document.querySelectorAll('[data-inspect-path]').forEach(tile=>{const chosen=tile===b;tile.classList.toggle('chosen',chosen);tile.setAttribute('aria-pressed',chosen);});updateUpgradeInspection(h);if(window.innerWidth<=760)$('library-detail').scrollIntoView({block:'start',behavior:'smooth'});});updateUpgradeInspection(h);
}
function updateUpgradeInspection(h){const {path:i,tier:n}=upgradeViewer,p=D.heroes[h.type].paths[i],theme=upgradeThemes[h.type][i],owned=n<h.u[i],state=game.upgradeState(h,i),cost=Math.ceil(p.costs[n]*(1-game.discount(h.x,h.y,'upgrade',h.id))),preview=h.u.map((v,j)=>j===i?n+1:0);const panel=$('library-detail');panel.style.setProperty('--path-color',theme[2]);panel.innerHTML=`<span class="detail-path">${theme[0]} ${p.name} · TIER ${n+1}</span><div class="library-portrait">${heroPortrait(h.type,preview)}</div><h3>${p.names[n]}</h3><span class="detail-badge">${owned?'✓ Already purchased':state.locked?state.reason:n===h.u[i]?'Next upgrade':'Preview · not purchased'}</span><p class="library-description">${p.descriptions[n]}</p><div class="detail-price">◈ ${cost.toLocaleString()} <small>gold${owned?' · current price':''}</small></div><p class="detail-note">${h.type==='leader'?'Damage and attack-speed bonuses are 25% stronger.':'Listed damage values receive the hero’s 25% damage bonus.'}${n===5?' Tier 6 unlocks the primary ability at 125% strength with a 20% shorter cooldown.':''}</p><p class="detail-note">Browse freely here. Return to your hero to buy upgrades.</p>`;}
window.addEventListener('keydown',event=>{if(!upgradeViewer)return;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closeUpgradeViewer();}else if(event.key==='Tab'){const items=[...document.querySelectorAll('#modal button')],first=items[0],last=items[items.length-1];if(event.shiftKey&&(document.activeElement===first||!items.includes(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}},true);
