const {test}=require('node:test');const assert=require('node:assert/strict');const {Game}=require('../engine.js');const D=require('../data.js');
function setup(u=[0,0,0,0]){const g=new Game();g.s.trees=[];g.s.money=100000;const h=g.addHero('abomination',190,230);assert.ok(h);h.u=u;h.clock=100;h.fireWhipAt=h.fireBoulderAt=100;g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=1000;return{g,h};}
function enemy(g,type='giant',p=230){const e=g.spawn(type,false,p);e.speed=0;return e;}
test('Flaming Abomination has 24 upgrades and Flurry of Blows is its first path',()=>{const {g,h}=setup();assert.equal(D.heroes.abomination.paths[0].name,'Flurry of Blows');assert.equal(g.addHero('abomination',460,640).type,'waterbeast');for(const p of D.heroes.abomination.paths)assert.equal(p.names.length,6);const e=enemy(g,'shaman');g.attack(h);assert.equal(e.maxHp-e.hp,30);assert.ok(e.effects.some(f=>f.kind==='burn'));});
test('Whip extends reach without extending punches and respects knockback limits and fire immunity',()=>{const {g,h}=setup([0,0,1,0]);assert.equal(g.range(h),220);assert.equal(g.abominationMelee(h),95);const e=enemy(g,'brute',430);assert.equal(g.attack(h),false);assert.ok(g.abominationWhip(h));assert.ok(e.hp<e.maxHp);e.hp=10000;for(let i=0;i<6;i++){g.s.time+=.5;g.abominationWhip(h);}assert.equal(e.displacementCount,3);const hound=enemy(g,'hellhound',450);g.s.time+=.5;g.abominationWhip(h);assert.equal(hound.hp,hound.maxHp);assert.equal(hound.displacementCount,undefined);});
test('Living Inferno locks to a legal path point, transforms, and stops other attacks',()=>{const {g,h}=setup([0,1,0,0]);assert.equal(g.setAbominationFlame(h,{x:900,y:300}),false);assert.equal(g.setAbominationFlame(h,{x:190,y:220}),false);assert.ok(g.setAbominationFlame(h,{x:190,y:160}));assert.equal(h.target,'flame');const e=enemy(g,'brute',230);g.tick(.71);assert.equal(g.attack(h),false);assert.ok(e.hp<e.maxHp);assert.ok(e.effects.some(f=>f.kind==='burn'));assert.deepEqual(g.abominationPosition(h),h.flameSpot);g.leaveAbominationFlame(h,'strong');assert.equal(h.target,'strong');g.tick(.71);assert.deepEqual(g.abominationPosition(h),{x:190,y:230});assert.ok(g.attack(h));});
test('Flame catches fast enemies crossing between ticks and respects hidden Shadows',()=>{const {g,h}=setup([0,1,0,0]);g.s.active=false;g.setAbominationFlame(h,{x:190,y:160});g.s.active=true;const e=enemy(g,'brute',170);g.tick(.01);e.p=290;Object.assign(e,g.position(e.p));g.tick(.01);assert.ok(e.hp<e.maxHp);const shadow=enemy(g,'shadow',230);g.s.time=6;shadow.born=0;g.tick(.01);assert.equal(shadow.hp,shadow.maxHp);});
test('Flame location persists across round end and save/load, but stun disables damage',()=>{const {g,h}=setup([0,1,0,0]);g.s.active=false;g.setAbominationFlame(h,{x:190,y:160});const saved=new Game(g.save()),ch=saved.s.heroes[0];assert.ok(saved.abominationFlame(ch));saved.s.active=true;const e=enemy(saved,'brute',230);ch.stunnedUntil=10;saved.tick(1);assert.equal(e.hp,e.maxHp);ch.stunnedUntil=0;saved.s.queue=[];saved.kill(e);saved.tick(.01);assert.equal(saved.s.active,false);assert.ok(saved.abominationFlame(ch));});
test('Boulder needs melee range, has delayed impact and shatters after hitting a capped crowd',()=>{const {g,h}=setup([0,0,0,1]);const far=enemy(g,'giant',500);assert.equal(g.abominationBoulder(h),false);for(let i=0;i<6;i++)enemy(g,'giant',230);assert.ok(g.abominationBoulder(h));assert.equal(g.attack(h),false);g.tick(.6);assert.equal(g.s.enemies.filter(e=>e.hp<e.maxHp).length,0);g.tick(.61);assert.equal(g.s.enemies.filter(e=>e.hp<e.maxHp).length,4);assert.ok(h.fireShatter);assert.equal(h.fireBoulder,undefined);assert.equal(far.hp,far.maxHp);});
test('Automatic boulder recharges for ten seconds after its windup',()=>{const {g,h}=setup([0,0,0,1]);enemy(g);h.fireBoulderAt=0;g.tick(.01);assert.equal(h.fireBoulderAt,11.21);g.tick(1.21);assert.equal(h.fireBoulder,undefined);g.tick(8);assert.equal(h.fireBoulder,undefined);g.tick(2);assert.ok(h.fireBoulder);});
test('All abomination tier-six abilities work and earlier tiers do not unlock abilities',()=>{for(let path=0;path<4;path++){const {g,h}=setup();h.u[path]=5;assert.equal(g.ability(h),null);h.u[path]=6;enemy(g);assert.ok(g.cast(h.id));assert.ok(h.cooldown>0);assert.equal(g.cast(h.id),false);}});

test('Two-handed whip replaces punches and low-tier boulders',()=>{const {g,h}=setup([2,0,1,0]);enemy(g);assert.equal(g.attack(h),false);assert.equal(g.abominationBoulder(h),false);h.fireWhipAt=0;g.updateAbominations(.01);assert.ok(h.fireWhip);assert.equal(g.attack(h),false);});
test('Tier-three flurry alternates exactly two punches with one exclusive whip',()=>{const {g,h}=setup([3,0,2,0]);enemy(g);assert.equal(g.abominationWhip(h),false);assert.ok(g.attack(h));assert.ok(g.attack(h));assert.equal(g.attack(h),false);assert.ok(g.abominationWhip(h));assert.equal(g.attack(h),false);g.s.time+=.5;assert.ok(g.attack(h));assert.ok(g.attack(h));assert.equal(g.attack(h),false);});
test('Tier-three boulders replace punches in the two-to-one whip cycle',()=>{const {g,h}=setup([0,0,2,3]);enemy(g);assert.equal(g.attack(h),false);assert.ok(g.abominationBoulder(h));g.s.time=1.3;g.updateAbominations(.01);assert.ok(g.abominationBoulder(h));g.s.time=2.6;g.updateAbominations(.01);assert.equal(g.abominationBoulder(h),false);assert.ok(g.abominationWhip(h));});

test('Flame crosspath counts two damaging pulses before whipping and saves its cycle',()=>{const {g,h}=setup([0,3,2,0]);g.s.active=false;assert.ok(g.setAbominationFlame(h,{x:190,y:160}));g.s.active=true;enemy(g);g.updateAbominations(.01);assert.equal(h.fireOtherAttacks,1);g.s.time=.6;g.updateAbominations(.01);assert.equal(h.fireOtherAttacks,2);const saved=new Game(g.save());assert.equal(saved.s.heroes[0].fireOtherAttacks,2);h.fireWhipAt=0;g.updateAbominations(.01);assert.ok(h.fireWhip);assert.equal(h.fireOtherAttacks,0);assert.equal(h.target,'flame');});
