const test=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../engine');
function setup(type,u){const g=new Game();g.s.money=1e6;g.s.trees=[];const water=['turtle','pirate','serpent','waterbeast'].includes(type);const h=g.addHero(type,water?460:190,water?640:230);h.x=190;h.y=230;h.u=u;h.clock=100;const e=g.spawn('giant',false,230);e.hp=e.maxHp=1e8;e.speed=0;e.blocks=0;g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=1000;return{g,h,e};}
test('Two punches then one whip repeats and persists mid-cycle',()=>{const{g,h}=setup('abomination',[0,0,1,0]);g.setAttackRotation(h,[{attack:'punch',count:2},{attack:'whip',count:1}]);assert.ok(g.attack(h));const copy=new Game(g.save()),ch=copy.s.heroes[0];assert.equal(ch.attackUsed,1);assert.ok(copy.attack(ch));assert.equal(copy.attack(ch),false);assert.ok(copy.abominationWhip(ch));assert.equal(copy.currentAttack(ch),'punch');copy.s.time+=.5;assert.ok(copy.attack(ch));});
test('All attacks can be disabled; abilities remain manually usable',()=>{const{g,h,e}=setup('abomination',[0,0,6,0]);g.setAttackRotation(h,[]);assert.equal(g.attack(h),false);assert.equal(g.abominationWhip(h),false);assert.equal(e.hp,e.maxHp);assert.ok(g.cast(h.id));assert.ok(e.hp<e.maxHp);assert.equal(g.currentAttack(h),'');});
test('Invalid configurations are rejected without losing the existing plan',()=>{const{g,h}=setup('knight',[0,0,1,0]);assert.ok(g.setAttackRotation(h,[{attack:'basic',count:2}]));for(const rows of [[{attack:'shell',count:1}],[{attack:'bash',count:-1}],[{attack:'bash',count:1.5}],[{attack:'bash',count:Infinity}]])assert.equal(g.setAttackRotation(h,rows),false);assert.equal(h.attackRotation[0].count,2);});
test('No targets, stun and cooldown waiting do not consume a rotation step',()=>{const{g,h,e}=setup('pirate',[0,0,1,0]);g.setAttackRotation(h,[{attack:'cannon',count:2},{attack:'rock',count:1}]);h.pirateCannonAt=100;g.updatePirates(.01);assert.equal(h.attackUsed,0);h.pirateCannonAt=0;e.dead=true;g.updatePirates(.01);assert.equal(h.attackUsed,0);e.dead=false;h.stunnedUntil=50;g.tick(.01);assert.equal(h.attackUsed,0);h.stunnedUntil=0;g.updatePirates(.01);assert.equal(h.attackUsed,1);assert.equal(g.attack(h),false);});
test('Knight schedule separates sword, shield, ground slam and holy swing',()=>{const{g,h,e}=setup('knight',[5,0,3,3]);for(const key of ['basic','bash','slam','radiant']){g.setAttackRotation(h,[{attack:key,count:1}]);h.count=0;const hp=e.hp;g.attack(h);assert.ok(e.hp<hp,key);if(key==='bash')assert.ok(e.effects.some(f=>f.kind==='stun'));}g.setAttackRotation(h,[]);const hp=e.hp;assert.equal(g.attack(h),false);assert.equal(e.hp,hp);});
test('Archer can disable normal volleys and use only Trick Shot',()=>{const{g,h,e}=setup('archer',[0,3,0,0]);g.setAttackRotation(h,[{attack:'trick',count:1}]);const hp=e.hp;g.attack(h);assert.equal(hp-e.hp,18*3*1.25);});
test('Rogue can disable daggers but still place traps, or choose only bombs',()=>{const{g,h,e}=setup('rogue',[0,0,1,3]);g.setAttackRotation(h,[{attack:'trap',count:1}]);assert.equal(g.attack(h),false);g.tick(.01);assert.ok(g.s.traps.length);g.setAttackRotation(h,[{attack:'bomb',count:1}]);const hp=e.hp;g.attack(h);assert.equal(hp-e.hp,40*1.25);});
test('Mage scheduled beam and lightning exclude unrelated primary damage',()=>{const{g,h,e}=setup('mage',[1,0,1,3]);g.setAttackRotation(h,[{attack:'beam',count:1}]);let hp=e.hp;g.attack(h);assert.equal(hp-e.hp,30*1.25);g.setAttackRotation(h,[{attack:'lightning',count:1}]);hp=e.hp;g.attack(h);assert.equal(hp-e.hp,15*1.25);});
test('Turtle rotation blocks disabled bite while allowing its shell',()=>{const{g,h}=setup('turtle',[1,0,1,0]);g.setAttackRotation(h,[{attack:'shell',count:1}]);assert.equal(g.attack(h),false);assert.ok(g.turtleShell(h));});
test('Water-form rotation counts an entire special once and waits for recovery',()=>{const{g,h}=setup('waterbeast',[1,1,0,0]);g.setAttackRotation(h,[{attack:'water1',count:1},{attack:'bite',count:2}]);assert.equal(g.attack(h),false);assert.ok(g.startWaterAction(h,1));assert.equal(g.currentAttack(h),'bite');assert.equal(g.attack(h),false);g.s.time=3.1;g.updateWaterBeasts(.1);assert.ok(g.attack(h));});
test('Tool Maker can disable rangs while keeping melee and disable turret firing',()=>{const{g,h}=setup('toolmaker',[1,2,0,1]);g.setAttackRotation(h,[{attack:'melee',count:1}]);assert.ok(g.attack(h));assert.equal(g.workshop().rangs.length,0);g.updateWorkshop(.01);assert.ok(g.workshop().turrets.length);assert.ok(g.workshop().turrets.every(t=>t.fired===undefined));});
test('Serpent schedule selects crosspath attacks and counts a stream only once',()=>{const{g,h}=setup('serpent',[0,1,0,1]);g.setAttackRotation(h,[{attack:'serpent3',count:1},{attack:'serpent1',count:1}]);g.updateSerpents();assert.ok(h.serpentStream);assert.equal(g.currentAttack(h),'serpent1');for(let i=0;i<5;i++){g.s.time+=.2;g.updateSerpents();}assert.ok(h.serpentDive);assert.equal(g.currentAttack(h),'serpent3');});
test('Saved targeting modes migrate without discarding the mode or aim priority',()=>{for(const[type,mode,u]of [['turtle','submerged',[0,0,0,1]],['abomination','flame',[0,1,0,0]]]){const{g,h}=setup(type,u);h.target=mode;h.flameSpot={x:190,y:160,p:230};const copy=new Game(g.save()),ch=copy.s.heroes[0];assert.equal(ch.target,'first');assert.equal(ch.mode,mode);ch.target='strong';assert.equal(ch.mode,mode);}});
test('Mode abilities use mode state and preserve target priority',()=>{const{g,h}=setup('turtle',[0,0,0,6]);h.target='strong';assert.ok(g.cast(h.id));assert.equal(h.mode,'submerged');assert.equal(h.target,'strong');});
test('Archer Lightning Leap is separately selectable without an arrow volley',()=>{const{g,h,e}=setup('archer',[0,0,3,0]);g.setAttackRotation(h,[{attack:'lightning',count:1}]);const hp=e.hp;g.attack(h);assert.equal(hp-e.hp,15*1.25);assert.equal(h.arrows,undefined);});
test('Upgrades do not silently enable omitted attacks in a saved custom rotation',()=>{const{g,h}=setup('pirate',[0,0,1,0]);g.setAttackRotation(h,[{attack:'rock',count:2}]);h.u[3]=1;assert.equal(g.attackAllowed(h,'hat'),false);g.resetAttackRotation(h);assert.equal(g.attackAllowed(h,'hat'),true);});
