const test=require('node:test'),assert=require('node:assert/strict'),{Game}=require('../engine.js'),D=require('../data.js');
const rules=[['knight',3,3],['archer',3,2],['rogue',0,2],['mage',3,1],['abomination',1,3],['turtle',3,2],['waterbeast',3,2]];
function setup(type='rogue',u=[0,0,0,0]){const g=new Game();g.s.money=1e6;g.s.trees=[];const water=['serpent','pirate','turtle','waterbeast'].includes(type),h=g.addHero(type,water?460:190,water?640:230);h.x=190;h.y=230;h.u=u;h.clock=100;const e=g.spawn('camoflauger',false,230);e.hp=e.maxHp=1e6;e.speed=0;return{g,h,e};}
test('Camoflauger debuts at 53 with triple regular Ghoul HP and seven-eighths speed',()=>{const g=new Game();assert.equal(D.enemies.camoflauger.hp,D.enemies.runner.hp*3);const a=g.spawn('camoflauger'),b=g.spawn('runner');assert.ok(Math.abs(a.speed/b.speed-7/8)<1e-10);for(let n=1;n<53;n++)assert.ok(!g.generateWave(n).includes('camoflauger'));assert.ok(g.generateWave(53).includes('camoflauger'));g.s.wave=52;g.s.nextWave=['skeleton'];g.s.camoflaugerWaveVersion=1;const copy=new Game(g.save());assert.ok(copy.s.nextWave.includes('camoflauger'));});
test('All seven detection unlocks apply to whole hero, crosspaths and higher tiers',()=>{for(const[type,p,tier]of rules){const{g,h,e}=setup(type);h.u[p]=tier-1;assert.equal(g.inRange(h).length,0,type);g.hit(e,20,h);assert.equal(e.hp,e.maxHp);assert.equal(g.apply(e,'slow',1,.2,h.id),false);for(const n of[tier,6]){h.u[p]=n;assert.ok(g.inRange(h).includes(e),type);const before=e.hp;g.hit(e,20,h);assert.ok(e.hp<before,type);assert.ok(g.apply(e,'slow',1,.2,h.id));assert.match(D.heroes[type].paths[p].descriptions[tier-1],/detect Camoflaugers/);}}});
test('Every unupgraded hero ignores camouflage and cannot damage, mark, push or kill it',()=>{for(const type of Object.keys(D.heroes).concat('waterbeast')){const{g,h,e}=setup(type);assert.equal(g.sorted(h,[e]).length,0,type);assert.equal(g.attack(h),false,type);g.area(e,100,500,h);for(const kind of['burn','poison','hunter','bounty','weak','stun','freeze','fear'])assert.equal(g.apply(e,kind,2,5,h.id),false);g.push(e,50,h);g.kill(e,h);assert.equal(e.hp,e.maxHp);assert.equal(e.p,230);assert.equal(e.dead,false);assert.equal(e.effects.length,0);}});
test('Undetected enemies do not consume projectile pierce or become chain lightning targets',()=>{const{g,h,e}=setup('archer',[0,0,3,0]);e.x=210;e.y=230;const visible=g.spawn('brute',false,260);visible.x=240;visible.y=230;assert.deepEqual(g.lineTargets(h,visible,200,20,1),[visible]);h.arrows=2;g.arrow(h,visible,10);assert.equal(e.hp,e.maxHp);h.u[3]=2;assert.deepEqual(g.lineTargets(h,visible,200,20,1),[e]);});
test('Rogue traps ignore camouflage until Pick a Target, then trigger normally',()=>{const{g,h,e}=setup('rogue',[0,0,2,0]);g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;h.clock=100;const t={owner:h.id,p:e.p,x:e.x,y:e.y,left:3,hit:[],level:2,end:100};g.s.traps.push(t);g.tick(.01);assert.equal(t.left,3);assert.deepEqual(t.hit,[]);h.u[0]=2;g.tick(.01);assert.equal(t.left,2);assert.ok(e.hp<e.maxHp);assert.ok(e.effects.some(f=>f.kind==='slow'));});
test('Workshop traps and goose decoys are not triggered by undetected enemies',()=>{for(const type of['toolmaker','serpent']){const{g,h,e}=setup(type,[0,0,3,0]);g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;h.clock=100;h.toolTrapAt=h.gooseAt=100;if(type==='toolmaker'){const w=g.workshop();w.traps.push({id:99,owner:h.id,kind:'jaw',p:e.p,x:e.x,y:e.y,power:1,end:100});g.updateWorkshop(.01);assert.equal(w.traps.length,1);}else{g.s.geese=[{owner:h.id,x:e.x,y:e.y,end:100,fear:true}];g.updateSerpents(.01);assert.equal(g.s.geese.length,1);}assert.equal(e.hp,e.maxHp);assert.equal(e.effects.length,0);}});
test('Dread Focus gates gaze and detection survives saving',()=>{const{g,h,e}=setup('waterbeast',[0,0,0,1]);assert.equal(g.startWaterAction(h,3),false);assert.equal(g.stopWithGaze(e,h,2),false);h.u[3]=2;assert.ok(g.startWaterAction(h,3));assert.ok(g.stopWithGaze(e,h,2));const copy=new Game(g.save());assert.ok(copy.canDetect(copy.s.heroes[0],copy.s.enemies[0]));});
