const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game,position,nearest,length}=require('../engine.js');
const D=require('../data.js');
function rich(){const g=new Game();g.s.money=100000;g.s.trees=[];return g;}
function hero(g,type,u=[0,0,0,0],x=190,y=230){if(type==='serpent'||D.heroes[type].waterOnly)g.map={...g.map,water:[[[x-30,y-30],[x+30,y-30],[x+30,y+30],[x-30,y+30]]]};const h=g.addHero(type,x,y);assert.ok(h,'valid placement');h.u=u;return h;}
function enemy(g,type='skeleton',p=190){const e=g.spawn(type);e.p=p;Object.assign(e,position(p));return e;}
test('starts with 200 money, 100 villagers and ten basic skeletons',()=>{const g=new Game();assert.equal(g.s.money,200);assert.equal(g.s.villagers,100);assert.deepEqual(g.s.nextWave,Array(10).fill('skeleton'));});
test('all 240 upgrades have names, explanations and prices',()=>{let total=0;for(const h of Object.values(D.heroes))for(const p of h.paths){assert.equal(p.names.length,6);assert.equal(p.costs.length,6);assert.equal(p.descriptions.length,6);total+=p.names.length;}assert.equal(total,240);});
test('placement avoids the path, trees, other heroes and map edges',()=>{const g=rich();g.s.trees=D.trees.map(t=>({...t}));assert.equal(g.canPlace(200,160),false);assert.equal(g.canPlace(145,265),false);assert.equal(g.canPlace(-1,500),false);g.s.trees=[];hero(g,'knight');assert.equal(g.canPlace(192,234),false);});
test('a second chosen path locks the other two, and only one reaches past two',()=>{const g=rich(),h=hero(g,'knight');assert.ok(g.upgrade(h.id,0));assert.ok(g.upgrade(h.id,1));assert.equal(g.upgrade(h.id,2),false);assert.ok(g.upgrade(h.id,0));assert.ok(g.upgrade(h.id,0));assert.ok(g.upgrade(h.id,1));assert.equal(g.upgrade(h.id,1),false);for(let i=0;i<3;i++)assert.ok(g.upgrade(h.id,0));assert.equal(g.upgrade(h.id,0),false);assert.deepEqual(h.u,[6,2,0,0]);assert.equal(g.ability(h).name,'Seismic Slam');});
test('knight, archer, mage and rogue have the agreed basic stats',()=>{for(const [type,damage,interval] of [['knight',10,1],['archer',12,1],['mage',15,1.5],['rogue',13,.7]]){const g=rich(),h=hero(g,type),s=g.stats(h);assert.equal(s.damage,damage*1.25);assert.equal(s.interval,interval);}});
test('selling returns 70% of actual spending',()=>{const g=rich(),h=hero(g,'knight');g.upgrade(h.id,0);assert.equal(h.spent,115);assert.equal(g.sell(h.id),80);assert.equal(g.s.heroes.length,0);});
test('clearing a tree costs 25 and removes its placement block',()=>{const g=new Game();assert.ok(g.removeTree(1));assert.equal(g.s.money,175);assert.equal(g.s.trees.some(t=>t.id===1),false);assert.equal(g.removeTree(1),false);});
test('Kill rewards stay full at low population',()=>{for(const population of [1,49,50,51,100]){const g=new Game();g.s.villagers=population;const e=enemy(g);g.hit(e,100);assert.equal(g.s.money,205);}});
test('armor reduces damage but cannot reduce an attack below one',()=>{const g=new Game(),e=enemy(g,'shield');g.hit(e,10);assert.equal(e.hp,139.25);g.hit(e,2);assert.equal(e.hp,138.25);g.hit(e,10,null,3);assert.equal(e.hp,128.25);});
test('giant blocks seven repeated effects and then takes reduced fear',()=>{const g=new Game(),e=enemy(g,'giant');for(let i=0;i<7;i++)assert.equal(g.apply(e,'freeze',1,1,1),false);assert.equal(e.blocks,0);assert.equal(e.effects.length,0);assert.ok(g.apply(e,'fear',5,1,1));assert.equal(e.effects[0].end,3.5);});
test('dragon blocks fifteen effects and then takes 1.75 second fear',()=>{const g=new Game(),e=enemy(g,'dragon');for(let i=0;i<15;i++)g.apply(e,'slow',1,.2,1);g.apply(e,'fear',5,1,1);assert.equal(e.effects[0].end,1.75);});
test('wave 100 is exactly one dragon followed by ten captains',()=>{const g=new Game();assert.deepEqual(g.generateWave(100),['dragon',...Array(10).fill('captain')]);for(let w=1;w<100;w++){const enemies=g.generateWave(w);assert.ok(!enemies.includes('dragon'));if(w<75)assert.ok(!enemies.includes('giant'));assert.ok(enemies.every(e=>D.enemies[e].wave<=w));}});
test('endless health and speed scale from the original values',()=>{const g=new Game();g.s.wave=110;const e=enemy(g,'dragon');assert.equal(e.maxHp,127237.5);assert.ok(Math.abs(e.speed-length/50*1.68*1.1)<.0001);assert.ok(g.generateWave(110).includes('dragon'));});
test('captain speed boosts stop at two',()=>{const g=new Game();g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;const e=enemy(g,'skeleton',200);for(let i=0;i<5;i++)enemy(g,'captain',210+i);g.tick(.01);assert.ok(Math.abs(e.p-200-e.speed*1.4*.01)<.0001);});
test('leaks remove villagers, zero loses the game',()=>{const g=new Game();g.s.active=true;g.s.villagers=2;const e=enemy(g,'shield',length-1);g.tick(.1);assert.equal(g.s.villagers,0);assert.equal(g.s.lost,true);assert.equal(g.s.active,false);});
test('a wave waits for all enemies, then awards 20 and saves next lineup',()=>{const g=new Game();g.startWave();g.s.queue=[];const e=enemy(g);g.tick(.01);assert.equal(g.s.active,true);g.hit(e,100);const money=g.s.money;g.tick(.01);assert.equal(g.s.active,false);assert.equal(g.s.money,money+20);assert.ok(g.s.nextWave.length>0);});
test('saved games round trip active waves, enemies, upgrades and cooldowns',()=>{const g=rich(),h=hero(g,'knight',[0,6,0,0]);g.startWave();const e=enemy(g,'brute',215);g.cast(h.id);g.tick(.1);const copy=new Game(g.save());assert.deepEqual(copy.save(),g.save());g.tick(.1);copy.tick(.1);assert.deepEqual(copy.save(),g.save());});
test('A Thousand Cuts hits multiple targets for 781.25 with 33.6-second wait',()=>{const g=rich(),h=hero(g,'knight',[0,6,0,0]);g.s.active=true;h.clock=100;g.s.queue=['skeleton'];g.s.spawnClock=100;const a=enemy(g,'giant',215),b=enemy(g,'giant',220);a.blocks=0;b.blocks=0;assert.ok(g.cast(h.id));assert.equal(h.cooldown,33.6);for(let i=0;i<61;i++)g.tick(1/60);assert.equal(a.hp,12718.75);assert.equal(b.hp,12718.75);assert.ok(a.effects.some(f=>f.kind==='stun'));});
test('second wind cannot reset second wind',()=>{const g=rich(),h=hero(g,'leader',[0,0,6,0]),other=hero(g,'leader',[0,0,6,0],85,225),knight=hero(g,'knight',[0,6,0,0],190,300);g.s.active=true;other.cooldown=80;knight.cooldown=30;assert.ok(g.cast(h.id));assert.equal(other.cooldown,80);assert.equal(h.cooldown,72);assert.equal(knight.cooldown,0);});
test('leaders do not attack and matching support does not stack',()=>{const g=rich(),h=hero(g,'knight'),l=hero(g,'leader',[1,0,0,0],85,225),l2=hero(g,'leader',[1,0,0,0],190,300);assert.equal(g.stats(h).damage,14.0625);assert.ok(Math.abs(g.stats(h).interval-1/1.125)<.0001);g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;const e=enemy(g,'giant',220);h.clock=100;g.tick(.1);assert.equal(e.hp,13500);});
test('every level-six ability can run without errors',()=>{for(const type of Object.keys(D.heroes))for(let p=0;p<4;p++){const g=rich(),u=[0,0,0,0];u[p]=6;const h=hero(g,type,u);const a=g.ability(h);if(!a)continue;g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;for(let i=0;i<10;i++){const e=enemy(g,'giant',190+i*5);if(type==='serpent')e.blocks=0;}const e=g.s.enemies[0],target=a.mode.startsWith('enemy')?e:a.mode.startsWith('point')?position(220):undefined;assert.ok(g.cast(h.id,target),a.name);for(let i=0;i<200;i++)g.tick(1/60);assert.ok(Number.isFinite(g.s.money),a.name);}});
test('overlapping fire patches from one mage cannot stack damage',()=>{const g=rich(),h=hero(g,'mage',[4,0,0,0]),e=enemy(g,'giant',220);e.speed=0;g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;h.clock=100;g.zone(h,'fire',e,85,4,10);g.tick(.1);g.zone(h,'fire',e,85,4,10);g.tick(.1);assert.equal(e.hp,13487.5);});
test('wave 100 wins only after the last enemy; endless needs a deliberate choice',()=>{const g=new Game();g.s.wave=99;g.s.nextWave=g.generateWave(100);assert.ok(g.startWave());g.s.queue=[];const e=enemy(g,'dragon');g.tick(.01);assert.equal(g.s.won,false);g.hit(e,e.maxHp);g.tick(.01);assert.equal(g.s.won,true);assert.equal(g.startWave(),false);g.s.endless=true;assert.ok(g.startWave());assert.equal(g.s.wave,101);});

function swarmGame(p=220){const g=new Game();g.s.active=true;g.s.queue=[];g.s.spawnClock=100;g.spawn('tiny');for(const e of g.s.enemies)e.p=p;g.arrangeSwarm(g.s.enemies);return g;}
test('tiny spawn makes ten individual enemies in a compact circle',()=>{const g=swarmGame(),members=g.s.enemies,c=position(220);assert.equal(members.length,10);assert.equal(new Set(members.map(e=>e.id)).size,10);assert.equal(new Set(members.map(e=>e.swarmId)).size,1);for(const e of members){assert.equal(e.hp,22.5);assert.ok(Math.abs(Math.hypot(e.x-c.x,e.y-c.y)-21)<1e-8);}g.hit(members[0],4);assert.equal(members[0].hp,18.5);assert.equal(members[1].hp,22.5);});
test('tiny deaths pay individually and shrink the surviving circle',()=>{const g=swarmGame();g.hit(g.s.enemies[0],22.5);assert.equal(g.s.money,202);g.tick(.01);assert.equal(g.s.enemies.length,9);const c=position(g.s.enemies[0].p);assert.ok(g.s.enemies.every(e=>Math.hypot(e.x-c.x,e.y-c.y)<21));});
test('chain lightning hits separate swarm members',()=>{const g=swarmGame();g.s.money=1000;g.s.trees=[];const h=hero(g,'mage',[0,0,3,0]);g.attack(h);assert.equal(g.s.enemies.filter(e=>e.hp===3.75).length,6);assert.equal(g.s.enemies.filter(e=>e.hp===22.5).length,4);});
test('slow affects one whole swarm but not a neighboring swarm',()=>{const g=swarmGame(),first=g.s.enemies.slice();g.spawn('tiny');const second=g.s.enemies.slice(10);for(const e of second)e.p=220;g.arrangeSwarm(second);g.apply(first[0],'slow',2,.5,99);g.tick(.1);for(const e of first)assert.ok(Math.abs(e.p-220-e.speed*.05)<1e-8);for(const e of second)assert.ok(Math.abs(e.p-220-e.speed*.1)<1e-8);});
test('one attack pushes a swarm once, even if it hits multiple members',()=>{const g=swarmGame(),batch=new Set();for(const e of g.s.enemies)g.push(e,42.5,{id:99},batch);assert.ok(g.s.enemies.every(e=>e.p===177.5));g.push(g.s.enemies[0],42.5,{id:99});assert.ok(g.s.enemies.every(e=>e.p===135));});
test('movement controls keep groups together and poison damage stays individual',()=>{for(const kind of ['stun','freeze','fear']){const g=swarmGame();g.apply(g.s.enemies[0],kind,1,1,99);g.tick(.1);assert.equal(new Set(g.s.enemies.map(e=>e.p)).size,1);assert.ok(kind==='fear'?g.s.enemies[0].p<220:g.s.enemies[0].p===220);}const g=swarmGame();g.apply(g.s.enemies[0],'poison',2,4,99,{wither:true});g.tick(.1);assert.equal(g.s.enemies[0].hp,22.1);assert.equal(g.s.enemies[1].hp,22.5);assert.equal(new Set(g.s.enemies.map(e=>e.p)).size,1);});
test('swarm saves resume identically and each survivor leaks separately',()=>{const g=swarmGame();g.s.introductionRewardPending=false;g.apply(g.s.enemies[0],'slow',2,.25,99);g.hit(g.s.enemies[0],22.5);g.tick(.1);const copy=new Game(g.save());g.tick(.1);copy.tick(.1);assert.deepEqual(copy.save(),g.save());for(const e of g.s.enemies)e.p=length-1;g.tick(.1);assert.equal(g.s.villagers,91);});
test('queued tiny entries spawn ten together and wave cap counts individuals',()=>{const g=new Game();g.s.nextWave=['tiny'];g.startWave();g.tick(.01);assert.equal(g.s.enemies.length,10);assert.equal(g.s.queue.length,0);for(let w=3;w<=200;w++){const list=g.generateWave(w);assert.ok(list.reduce((n,k)=>n+(k==='tiny'?10:1),0)<=440);}});
test('old saves bundle tiny queues without multiplying every old tiny by ten',()=>{const g=new Game(),save=g.save();delete save.swarmVersion;save.nextWave=[...Array(12).fill('tiny'),'runner'];const migrated=new Game(save);assert.deepEqual(migrated.s.nextWave,['tiny','tiny','runner']);assert.deepEqual(new Game(migrated.save()).save(),migrated.save());});
test('health increase migrates old wounded enemies once, including endless scaling',()=>{const g=new Game();g.s.wave=110;for(const type of Object.keys(D.enemies))g.spawn(type);const old=g.save();delete old.healthBalanceVersion;for(const e of old.enemies){e.maxHp/=2.25;e.hp=e.maxHp*.4;}const updated=new Game(old);for(const e of updated.s.enemies){assert.ok(Math.abs(e.maxHp-D.enemies[e.type].hp*1.5*g.enemyMilestoneHealth(e.type))<1e-7);assert.ok(Math.abs(e.hp/e.maxHp-.4)<1e-12);}assert.deepEqual(new Game(updated.save()).save(),updated.save());});
test('all skeletons move 68 percent faster and old saves migrate only once',()=>{const previous={skeleton:30,tiny:24,runner:9,shield:36,brute:45,captain:30,shaman:36,giant:60,dragon:50};for(const wave of [1,110]){const g=new Game();g.s.wave=wave;for(const type of Object.keys(previous)){const e=g.spawn(type),expected=length/previous[type]*1.68*(1+Math.max(0,wave-100)*.01);assert.ok(Math.abs(e.speed-expected)<1e-8,type);}const old=g.save();delete old.speedBalanceVersion;for(const e of old.enemies)e.speed/=1.68;const updated=new Game(old);for(let i=0;i<old.enemies.length;i++)assert.ok(Math.abs(updated.s.enemies[i].speed-old.enemies[i].speed*1.68)<1e-8);assert.deepEqual(new Game(updated.save()).save(),updated.save());}});
test('mixed difficulty spends the increased random-wave budget',()=>{const costs={skeleton:1,tiny:4,runner:1.2,shield:3,brute:6,ironling:8,camoflauger:7,fusion:26,headless:8,shadow:12,hellhound:8,werewolf:14,screecher:100,captain:12,shaman:11,giant:65,dragon:180},g=new Game();for(let wave=16;wave<75;wave++){let budget=Math.floor(8+wave*2.1+Math.pow(wave,1.38)*.24);if(wave%10===0)budget=Math.round(budget*1.35);budget=Math.round(budget*22/15);const lineup=g.generateWave(wave),spent=lineup.reduce((sum,k)=>sum+costs[k],0),reserved=lineup.reduce((n,k)=>n+(k==='tiny'?10:k==='fusion'?51:1),0);assert.ok(spent<=budget+1e-8&&(budget-spent<1.00001||reserved===440),`wave ${wave}`);}});
test('mixed difficulty migrates wounded enemies once and preserves active wave queues',()=>{const g=new Game();g.startWave();const e=g.spawn('skeleton');const old=g.save();old.healthBalanceVersion=1;delete old.waveBalanceVersion;old.enemies[0].maxHp=42;old.enemies[0].hp=21;const updated=new Game(old);assert.equal(updated.s.enemies[0].maxHp,63);assert.equal(updated.s.enemies[0].hp,31.5);assert.deepEqual(updated.s.queue,old.queue);assert.deepEqual(new Game(updated.save()).save(),updated.save());const between=new Game().save();between.wave=20;between.nextWave=['skeleton'];delete between.waveBalanceVersion;assert.ok(new Game(between).s.nextWave.length>1);});
test('hero buff applies once before armor and also strengthens burn and poison',()=>{for(const [type,kind] of [['knight','burn'],['rogue','poison']]){const g=rich(),h=hero(g,type),e=enemy(g,'brute');e.armor=3;const initial=e.hp;g.hit(e,10,h);assert.equal(initial-e.hp,9.5);g.s.active=true;g.s.queue=[];g.s.spawnClock=100;h.clock=100;e.speed=0;g.apply(e,kind,2,4,h.id);const before=e.hp;g.tick(.5);assert.equal(before-e.hp,2.5);const copy=new Game(g.save());assert.equal(copy.stats(copy.s.heroes[0]).damage,g.stats(h).damage);}});
test('leader abilities boost bonus amounts by 25 percent',()=>{const g=rich(),h=hero(g,'knight'),l=hero(g,'leader',[6,0,0,0],85,225);g.s.active=true;assert.ok(g.cast(l.id));assert.equal(g.buffs(h).speed,2.5625);assert.equal(g.stats(h).damage,32.03125);l.roar=0;l.u=[0,0,0,6];l.cooldown=0;assert.ok(g.cast(l.id));assert.equal(g.buffs(h).speed,1.46875);l.festival=0;l.u=[0,0,3,0];const e=enemy(g,'giant',190);assert.equal(g.multiplier(e,h),1.1875);});
test('graves sell unlimited villagers with rising prices and no bulk discount',()=>{const g=rich();g.s.villagers=99;const money=g.s.money;assert.ok(g.buyVillagers(1));assert.equal(g.s.villagers,100);assert.ok(g.buyVillagers(25));assert.equal(g.s.villagers,125);assert.equal(g.s.money,money-19200);assert.ok(g.buyVillagers(25));assert.equal(g.s.money,money-44200);assert.equal(new Game(g.save()).s.villagers,150);});
test('villager purchases reject invalid quantities, insufficient funds, and defeat',()=>{const g=new Game();for(const n of [0,-1,1.5,NaN,Infinity,'1',Number.MAX_SAFE_INTEGER,21]){const before=g.save();assert.equal(g.buyVillagers(n),false);assert.deepEqual(g.save(),before);}g.s.lost=true;assert.equal(g.buyVillagers(1),false);});
test('legacy villager purchases do not change gold reward rates',()=>{const g=new Game();g.s.active=true;g.s.villagers=50;assert.ok(g.buyVillagers(1));assert.equal(g.s.money,190);g.hit(g.spawn('skeleton'),100);assert.equal(g.s.money,195);});
test('revival prices use strict above thresholds and bulk purchases match individual buys',()=>{for(const [population,price,next] of [[65,10,20],[85,20,100],[100,100,500],[110,500,1000],[111,1000,1000]]){const g=rich();g.s.villagers=population;assert.equal(g.villagerPrice(),price);assert.equal(g.villagerPurchaseCost(2),price+next);g.s.money=price+next-1;assert.equal(g.affordableVillagers(),1);assert.equal(g.buyVillagers(2),false);g.s.money++;assert.equal(g.affordableVillagers(),2);assert.ok(g.buyVillagers(2));assert.equal(g.s.money,0);}const bulk=rich();bulk.s.villagers=60;const singles=new Game(bulk.save());const cost=bulk.villagerPurchaseCost(70);assert.ok(bulk.buyVillagers(70));for(let i=0;i<70;i++)assert.ok(singles.buyVillagers(1));assert.equal(bulk.s.money,singles.s.money);assert.equal(bulk.s.villagers,singles.s.villagers);assert.equal(100000-bulk.s.money,cost);});
test('affordability and price fall again when villagers are lost',()=>{const g=new Game();g.s.money=99;g.s.villagers=86;assert.equal(g.affordableVillagers(),0);g.s.villagers=65;assert.equal(g.villagerPrice(),10);assert.equal(g.affordableVillagers(),5);assert.equal(g.villagerPurchaseCost(5),90);});
test('first fifteen waves have smaller budgets and more time between spawns',()=>{const costs={skeleton:1,tiny:4,runner:1.2,shield:3,brute:6,ironling:8,camoflauger:7,fusion:26,headless:8,shadow:12,hellhound:8,werewolf:14,screecher:100,captain:12,shaman:11,giant:65,dragon:180};for(let wave=1;wave<=16;wave++){const g=new Game();const lineup=g.generateWave(wave);if(wave>=2&&wave<=15){let previous=Math.floor(8+wave*2.1+Math.pow(wave,1.38)*.24);if(wave%10===0)previous=Math.round(previous*1.35);previous=Math.round(previous*22/15);const spent=lineup.reduce((sum,k)=>sum+costs[k],0);assert.ok(spent<=Math.round(previous*.9)+1e-8,`wave ${wave} should be lighter`);if(wave===2)assert.equal(lineup.length,11);}g.s.wave=wave-1;g.s.nextWave=lineup;g.startWave();g.tick(.01);if(wave===1)assert.equal(g.s.spawnClock,2.5);else if(wave<=15)assert.ok(g.s.spawnClock>=Math.max(.3,1.6-wave*.009)*1.0999);else assert.equal(g.s.spawnClock,Math.max(.3,1.6-wave*.009));}});
test('early-wave update refreshes only prepared early waves and preserves active saves',()=>{for(const [wave,active,refresh] of [[4,false,true],[15,false,false],[4,true,false]]){const save=new Game().save();save.wave=wave;save.active=active;save.nextWave=['dragon'];save.queue=['runner','skeleton'];delete save.earlyWaveBalanceVersion;const copy=new Game(save);assert.equal(copy.s.nextWave.includes('dragon'),!refresh);assert.deepEqual(copy.s.queue,save.queue);assert.deepEqual(new Game(copy.save()).save(),copy.save());}});
function limitHeroes(g,type,count,upgrades){const result=[];for(let y=100;y<640&&result.length<count;y+=50)for(let x=50;x<980&&result.length<count;x+=50)if(g.canPlace(x,y)){const h=g.addHero(type,x,y);h.u=upgrades.slice();result.push(h);}assert.equal(result.length,count);return result;}
test('each path counts only exact tiers and upgrading frees the previous tier slot',()=>{const g=rich(),heroes=limitHeroes(g,'knight',7,[3,0,0,0]);for(const h of heroes.slice(0,3))assert.ok(g.upgrade(h.id,0));const spent=g.s.money;assert.equal(g.upgrade(heroes[3].id,0),false);assert.equal(g.s.money,spent);assert.match(g.upgradeState(heroes[3],0).reason,/3 Knights at level 4 on this path/);for(const h of heroes.slice(0,2))assert.ok(g.upgrade(h.id,0));assert.equal(g.upgrade(heroes[2].id,0),false);assert.ok(g.upgrade(heroes[3].id,0),'Tier five frees a tier-four slot');assert.ok(g.upgrade(heroes[0].id,0));assert.equal(g.upgrade(heroes[1].id,0),false);assert.ok(g.upgrade(heroes[2].id,0),'Tier six frees a tier-five slot');for(const h of heroes.slice(4,6))assert.ok(g.upgrade(h.id,0));assert.deepEqual([4,5,6].map(t=>g.s.heroes.filter(h=>h.u[0]===t).length),[3,2,1]);const copy=new Game(g.save());assert.equal(copy.upgrade(heroes[6].id,0),false);assert.equal(copy.upgrade(heroes[3].id,0),false);assert.equal(copy.upgrade(heroes[1].id,0),false);copy.sell(heroes[0].id);assert.ok(copy.upgrade(heroes[1].id,0));assert.ok(copy.upgrade(heroes[3].id,0));assert.ok(copy.upgrade(heroes[6].id,0));});
test('upgrade limits are separate for each hero type and path and persist on load',()=>{const g=rich();limitHeroes(g,'knight',1,[6,0,0,0]);const otherPath=limitHeroes(g,'knight',1,[0,5,0,0])[0],otherType=limitHeroes(g,'mage',1,[5,0,0,0])[0];assert.ok(g.upgrade(otherPath.id,1));assert.ok(g.upgrade(otherType.id,0));const blocked=limitHeroes(g,'knight',1,[5,0,0,0])[0],copy=new Game(g.save());assert.equal(copy.upgrade(blocked.id,0),false);assert.equal(copy.s.heroes.length,4);});
test('older saves keep existing over-limit heroes but block further purchases',()=>{const g=rich();limitHeroes(g,'knight',3,[6,0,0,0]);const candidate=limitHeroes(g,'knight',1,[5,0,0,0])[0];const copy=new Game(g.save());assert.equal(copy.s.heroes.filter(h=>h.u[0]===6).length,3);assert.equal(copy.upgrade(candidate.id,0),false);});
test('temporary attack-speed bonus applies in rounds 1 through 15 only',()=>{for(const type of ['knight','archer','rogue','mage']){const g=rich(),h=hero(g,type),normal=g.stats(h).interval;for(const wave of [1,7,15]){g.s.wave=wave;assert.ok(Math.abs(g.stats(h).interval-normal/1.15)<1e-12);const copy=new Game(g.save());assert.equal(copy.stats(copy.s.heroes[0]).interval,g.stats(h).interval);}for(const wave of [16,100,110]){g.s.wave=wave;assert.equal(g.stats(h).interval,normal);}}});
test('early speed bonus combines with upgrades and leaders without changing cooldowns',()=>{const g=rich(),h=hero(g,'knight',[0,4,0,0]);hero(g,'leader',[0,0,2,0],85,225);g.s.wave=15;assert.ok(Math.abs(g.stats(h).interval-.4/1.125/1.15)<1e-12);assert.equal(g.buffs(h).cd,.9);g.s.wave=16;assert.equal(g.stats(h).interval,.4/1.125);assert.equal(g.buffs(h).cd,.9);});
test('all paths unlock only one primary ability at six, including saved heroes',()=>{for(const type of Object.keys(D.heroes))for(let path=0;path<4;path++)for(const tier of [3,4,5,6]){const g=rich(),u=[0,0,0,0];u[path]=tier;const h=hero(g,type,u);g.s.active=true;const e=enemy(g,'giant',220);e.blocks=0;if(type==='serpent')enemy(g,'skeleton',180);assert.equal(g.abilities(h).length,tier===6?1:0);assert.equal(g.ability(h,'secondary'),null);assert.equal(g.cast(h.id,e,'secondary'),false);const a=g.ability(h);if(tier<6){assert.equal(a,null);assert.equal(g.cast(h.id,e),false);}else{assert.equal(a.power,1.25);const target=a.mode.startsWith('enemy')?e:a.mode.startsWith('point')?position(220):undefined;assert.ok(g.cast(h.id,target));}const copy=new Game(g.save());assert.equal(copy.abilities(copy.s.heroes[0]).length,tier===6?1:0);}});
test('Perfect Shot damage scales once at each tier and preserves original passives',()=>{for(const [tier,damage] of [[6,3125]]){const g=rich(),h=hero(g,'archer',[0,0,0,tier]),e=enemy(g,'dragon',220);g.s.active=true;const before=e.hp;assert.ok(g.cast(h.id,e));assert.equal(before-e.hp,damage);assert.equal(g.range(h),2000);}});
test('Second Wind scales cooldown reduction and cannot reset reset abilities',()=>{for(const [tier,fraction] of [[6,1]]){const g=rich(),h=hero(g,'leader',[0,0,tier,0]),ally=hero(g,'knight',[0,6,0,0],190,300),other=hero(g,'leader',[0,0,6,0],85,225);g.s.active=true;ally.cooldown=40;ally.secondaryCooldown=30;other.cooldown=60;other.secondaryCooldown=50;h.timing=100;other.timing=100;assert.ok(g.cast(h.id));assert.ok(Math.abs(ally.cooldown-40*(1-fraction))<1e-8);assert.equal(ally.secondaryCooldown,30);assert.equal(other.cooldown,60);assert.equal(other.secondaryCooldown,50);}});
test('upgrading to six unlocks primary while old secondary cooldowns never unlock a second ability',()=>{const g=rich(),h=hero(g,'knight',[0,4,0,0]);g.s.active=true;h.cooldown=12;h.secondaryCooldown=8;assert.equal(g.cast(h.id),false);assert.ok(g.upgrade(h.id,1));assert.equal(g.abilities(h).length,0);assert.ok(g.upgrade(h.id,1));assert.equal(h.cooldown,12);const copy=new Game(g.save()),saved=copy.s.heroes[0];assert.equal(copy.abilities(saved).length,1);assert.equal(copy.cast(saved.id,undefined,'secondary'),false);assert.equal(saved.cooldown,12);});
test('Fusion Skeleton has two-thirds of a Weaker Cyclops health and spawns five separate swarms after bursting',()=>{const g=new Game();g.s.wave=20;g.s.active=true;g.s.queue=[];const e=g.spawn('fusion',false,700);assert.equal(e.hp,D.enemies.brute.hp*2/3);g.hit(e,10000);g.kill(e);assert.equal(g.s.fusionBursts.length,1);g.tick(.6);assert.equal(g.s.enemies.length,0);assert.equal(g.s.active,true);const saved=new Game(g.save());g.tick(.61);saved.tick(.61);assert.deepEqual(saved.save(),g.save());assert.equal(g.s.enemies.length,50);assert.equal(new Set(g.s.enemies.map(e=>e.swarmId)).size,5);for(const member of g.s.enemies){assert.equal(g.swarm(member).length,10);assert.ok(member.p>=700);assert.equal(member.hp,D.enemies.tiny.hp);}assert.equal(g.s.fusionBursts.length,0);assert.equal(g.s.active,true);for(const member of g.s.enemies)g.hit(member,1000);g.tick(.01);assert.equal(g.s.active,false);});
test('Fusion bursts pause with game time, do not spawn on leaking, and survive selling a hero',()=>{const g=rich();g.s.active=true;g.s.queue=[];const h=hero(g,'knight'),e=g.spawn('fusion',false,300);g.hit(e,10000,h);g.sell(h.id);g.s.active=false;g.tick(5);assert.equal(g.s.fusionBursts.length,1);assert.equal(g.s.enemies.filter(e=>!e.dead).length,0);g.s.active=true;g.tick(1.21);assert.equal(g.s.enemies.length,50);const leak=new Game();leak.s.active=true;leak.s.queue=[];leak.s.seen=['fusion'];leak.spawn('fusion',false,length-.1);leak.tick(.1);assert.equal(leak.s.villagers,95);assert.equal(leak.s.fusionBursts.length,0);});
test('Fusion swarms retain independent group control and endless health scaling',()=>{const g=new Game();g.s.wave=110;g.s.active=true;g.s.queue=[];const e=g.spawn('fusion',false,400);assert.equal(e.hp,405*g.enemyMilestoneHealth('fusion'));g.hit(e,99999);g.tick(1.21);const first=g.s.enemies[0],last=g.s.enemies[49];assert.equal(first.hp,D.enemies.tiny.hp*1.5*g.enemyMilestoneHealth('tiny'));g.apply(first,'slow',2,.5,99);assert.ok(g.swarm(first).every(e=>e.effects.some(f=>f.kind==='slow')));assert.equal(last.effects.length,0);for(let w=1;w<20;w++)assert.ok(!g.generateWave(w).includes('fusion'));});

test('headless zombie throws once at one-third HP, rolls, screams, and stuns strongest nearby hero for fifteen seconds',()=>{const g=rich(),a=hero(g,'knight',[4,0,0,0]),b=hero(g,'archer',[0,0,0,0],340,230);a.spent=500;b.spent=100;g.s.active=true;g.s.queue=[];const e=enemy(g,'headless');e.speed=0;g.hit(e,119);assert.equal(g.s.zombieHeads.length,0);g.hit(e,1);assert.equal(e.headThrown,true);assert.equal(g.s.zombieHeads.length,1);g.hit(e,1);assert.equal(g.s.zombieHeads.length,1);a.clock=b.clock=100;const head=g.s.zombieHeads[0];assert.equal(head.toX,(e.x+a.x)/2);const copy=new Game(g.save());copy.tick(1.2);assert.equal(copy.s.heroes[0].stunnedUntil,undefined);assert.equal(copy.s.zombieHeads[0].x,head.toX);copy.tick(1.01);const target=copy.s.heroes[0];assert.equal(copy.s.zombieHeads.length,0);assert.equal(target.stunnedUntil,copy.s.time+15);assert.equal(copy.s.heroes[1].stunnedUntil,undefined);assert.equal(copy.attack(target),false);assert.equal(copy.cast(target.id),false);const clock=target.clock;copy.tick(14);assert.equal(target.clock,clock);copy.tick(1.01);assert.ok(target.clock<clock);});
test('headless head survives body death, respects pause, and resolves without any nearby hero',()=>{const g=rich();g.s.active=true;g.s.queue=[];const e=enemy(g,'headless');g.hit(e,999);assert.equal(g.s.zombieHeads.length,1);g.tick(.1);assert.equal(g.s.active,true);const saved=g.save();g.s.active=false;g.tick(20);assert.equal(g.s.time,saved.time);g.s.active=true;g.tick(2.2);assert.equal(g.s.zombieHeads.length,0);assert.equal(g.s.active,false);});
test('stun suppresses allied buffs, weakening effects, ongoing damage and traps for ten seconds',()=>{const g=rich(),leader=hero(g,'leader',[5,0,0,0]),knight=hero(g,'knight',[0,0,0,0],340,230),e=enemy(g);g.s.active=true;g.s.queue=[];e.speed=0;leader.stunnedUntil=10;leader.roar=20;leader.roarPower=1;assert.equal(g.buffs(knight).damage,D.heroDamageScale);g.apply(e,'weak',20,.25,leader.id);assert.equal(e.effects.length,0);e.effects.push({kind:'weak',owner:leader.id,end:20,value:.25},{kind:'poison',owner:leader.id,end:20,value:10});knight.clock=100;const hp=e.hp;g.tick(1);assert.equal(e.hp,hp);assert.equal(e.effects.length,2);assert.equal(g.multiplier(e,knight),1);g.tick(9.1);assert.ok(g.buffs(knight).damage>D.heroDamageScale);assert.ok(e.hp<hp);});
test('headless unlocks at round 30 and emits a single scream when the roll ends',()=>{const g=rich();assert.equal(D.enemies.headless.wave,30);for(let n=1;n<30;n++)assert.ok(!g.generateWave(n).includes('headless'));assert.ok(g.generateWave(30).includes('headless'));g.s.active=true;g.s.queue=[];const e=enemy(g,'headless');e.speed=0;g.hit(e,120);g.events=[];g.tick(1.19);assert.equal(g.events.filter(e=>e.type==='zombieScream').length,0);g.tick(.02);assert.equal(g.events.filter(e=>e.type==='zombieScream').length,1);const copy=new Game(g.save());copy.tick(.4);assert.equal(copy.events.filter(e=>e.type==='zombieScream').length,0);g.tick(.4);assert.equal(g.events.filter(e=>e.type==='zombieScream').length,1);});
test('heads skip stunned heroes on throw and recheck targets when screaming finishes',()=>{const g=rich(),a=hero(g,'leader'),b=hero(g,'knight',[0,0,0,0],190,300);a.spent=1000;b.spent=100;a.stunnedUntil=100;g.s.active=true;g.s.queue=[];b.clock=100;const e=enemy(g,'headless');e.speed=0;g.hit(e,120);assert.equal(g.s.zombieHeads[0].toY,(e.y+b.y)/2);a.stunnedUntil=0;b.stunnedUntil=100;g.tick(2.3);assert.equal(a.stunnedUntil,g.s.time+15);assert.equal(b.stunnedUntil,100);const e2=enemy(g,'headless');e2.speed=0;g.hit(e2,120);const before=[a.stunnedUntil,b.stunnedUntil];g.tick(2.3);assert.deepEqual([a.stunnedUntil,b.stunnedUntil],before);assert.equal(g.s.zombieHeads.length,0);});
test('round completion clears all remaining stuns before saving or starting the next round',()=>{const g=rich(),h=hero(g,'leader');g.s.active=true;g.s.queue=[];h.stunnedUntil=100;g.tick(.01);assert.equal(g.s.active,false);assert.equal(h.stunnedUntil,0);const copy=new Game(g.save());assert.equal(copy.s.heroes[0].stunnedUntil,0);copy.startWave();assert.ok(copy.activeHeroes().some(a=>a.id===h.id));const saved=g.save();saved.heroes[0].stunnedUntil=100;assert.equal(new Game(saved).s.heroes[0].stunnedUntil,0);});
test('headless zombies have half the wave-selection weight of other eligible types',()=>{let headless=0,wraith=0;for(let seed=1;seed<=500;seed++){const g=rich();g.s.seed=seed*7919;for(const type of g.generateWave(60)){if(type==='headless')headless++;if(type==='shaman')wraith++;}}assert.ok(headless>wraith*.35&&headless<wraith*.7,`${headless} headless vs ${wraith} wraiths`);});
test('Shadow Goul starts at round 45 and cycles five seconds immune then two seconds vulnerable',()=>{const g=rich();g.s.active=true;g.s.queue=[];const e=enemy(g,'shadow');assert.equal(D.enemies.shadow.wave,45);assert.ok(e.speed<length/D.enemies.skeleton.time);for(const n of [1,35,44])assert.ok(!g.generateWave(n).includes('shadow'));g.tick(4.9);assert.equal(g.shadowImmune(e),false);g.apply(e,'fear',20,1,99);g.apply(e,'poison',20,10,99);g.tick(.1);assert.equal(g.shadowImmune(e),true);assert.equal(e.effects.length,0);const hp=e.hp,p=e.p;g.hit(e,10000,null,999);g.hit(e,10000,null,999,true);assert.equal(e.hp,hp);for(const kind of ['slow','fear','stun','freeze','poison','burn','weak','hunter','bounty'])assert.equal(g.apply(e,kind,10,1,99),false);g.push(e,80,{id:99});assert.equal(e.p,p);g.tick(4.9);assert.ok(e.p>p);assert.equal(g.shadowImmune(e),true);g.tick(.1);assert.equal(g.shadowImmune(e),false);g.hit(e,1);assert.equal(e.hp,hp-1);g.apply(e,'stun',20,1,99);g.tick(1.9);assert.equal(g.shadowImmune(e),false);g.tick(.1);assert.equal(g.shadowImmune(e),true);assert.equal(e.effects.length,0);});
test('Shadow Goul timing saves, pauses and starts independently for each spawn',()=>{const g=rich();g.s.active=true;g.s.queue=[];const e=enemy(g,'shadow');g.tick(6);const copy=new Game(g.save());assert.equal(copy.shadowImmune(copy.s.enemies[0]),true);const e2=enemy(g,'shadow');assert.equal(g.shadowImmune(e2),false);g.s.active=false;g.tick(10);assert.equal(g.s.time,6);g.s.active=true;g.tick(4);copy.tick(4);assert.equal(g.shadowImmune(e),false);assert.equal(copy.shadowImmune(copy.s.enemies[0]),false);assert.equal(e.hp,copy.s.enemies[0].hp);});
test('Hell Hound appears at 55, runs three times Ghoul speed, and its explosion respects radius and defenses',()=>{const g=rich();g.s.active=true;g.s.queue=[];const h=enemy(g,'hellhound'),ghoul=enemy(g,'runner',1000),near=enemy(g,'brute',220),far=enemy(g,'brute',800),guard=enemy(g,'shield',230),shadow=enemy(g,'shadow',240);shadow.born=-5;assert.equal(D.enemies.hellhound.wave,55);assert.ok(Math.abs(h.speed-ghoul.speed*3)<1e-9);for(const n of [35,45,54])assert.ok(!g.generateWave(n).includes('hellhound'));const hp=near.hp,guardHp=guard.hp,shadowHp=shadow.hp,farHp=far.hp;g.hit(h,9999);assert.equal(near.hp,hp-225);assert.equal(guard.hp,guardHp-222);assert.equal(shadow.hp,shadowHp);assert.equal(far.hp,farHp);assert.equal(g.effects.filter(f=>f.type==='explosion').length,1);assert.equal(g.effects.find(f=>f.type==='explosion').radius,240);g.kill(h);assert.equal(near.hp,hp-225);});
test('Hell Hound explosions chain once per hound and award each kill once',()=>{const g=rich();const hounds=Array.from({length:20},()=>enemy(g,'hellhound')),before=g.s.money;g.hit(hounds[0],9999);assert.ok(hounds.every(e=>e.dead));assert.equal(g.s.money-before,20*D.enemies.hellhound.reward);assert.equal(g.events.filter(e=>e.type==='explosion').length,20);});
test('Hell Hound escaping does not explode and saved movement retains its speed',()=>{const g=rich();g.s.seen=['hellhound'];g.s.active=true;g.s.queue=[];const h=enemy(g,'hellhound',length-1);const copy=new Game(g.save());assert.equal(copy.s.enemies[0].speed,h.speed);g.tick(.1);assert.equal(g.s.villagers,97);assert.equal(g.events.filter(e=>e.type==='explosion').length,0);});
test('every hero attack and tier-six ability leaves a shadow-state Goul health and shield untouched',()=>{for(const type of Object.keys(D.heroes))for(let path=0;path<4;path++){const g=rich(),u=[0,0,0,0];u[path]=6;const h=hero(g,type,u),e=enemy(g,'shadow',220);e.speed=0;e.shield=40;g.s.active=true;g.s.wave=55;g.s.queue=[];g.s.time=5;g.s.waveTime=5;const hp=e.hp;g.attack(h);const a=g.ability(h),target=a.mode.startsWith('enemy')?e:a.mode.startsWith('point')?{x:e.x,y:e.y}:undefined;g.cast(h.id,target);g.kill(e,h);for(let i=0;i<180;i++)g.tick(1/60);assert.equal(e.hp,hp,type+' path '+path);assert.equal(e.shield,40);assert.equal(e.dead,false);assert.equal(e.effects.length,0);}});
test('shadow immunity blocks traps, persistent zones, preexisting poison, burn and chained hound explosions',()=>{const g=rich(),h=hero(g,'rogue',[0,0,6,0]),e=enemy(g,'shadow',220);g.s.active=true;g.s.queue=[];g.s.time=5;e.speed=0;e.effects=[{kind:'burn',owner:h.id,end:20,value:1000},{kind:'poison',owner:h.id,end:20,value:1000}];g.trap(h,{x:e.x,y:e.y,p:e.p},true);g.zone(h,'fire',e,85,4,1000);g.zone(h,'meteor',e,85,4,1000);const hp=e.hp;for(let i=0;i<3;i++)enemy(g,'hellhound',220);g.hit(g.s.enemies.find(o=>o.type==='hellhound'),99999);for(let i=0;i<180;i++)g.tick(1/60);assert.equal(e.hp,hp);assert.equal(e.dead,false);assert.equal(e.effects.length,0);g.s.time=10;g.hit(e,1);assert.equal(e.hp,hp-1);});
test('enemies have a combined lifetime limit of three fears and knockbacks that persists on save',()=>{const g=rich(),e=enemy(g,'brute',500);assert.ok(g.apply(e,'fear',1,1,99));g.push(e,20,{id:99});assert.ok(g.apply(e,'fear',2,1,100));assert.equal(e.displacementCount,3);const p=e.p;assert.equal(g.apply(e,'fear',50,1,99),false);g.push(e,20,{id:99});assert.equal(e.p,p);assert.ok(g.apply(e,'stun',1,1,99));assert.ok(g.apply(e,'slow',1,.2,99));const copy=new Game(g.save()),saved=copy.s.enemies[0];assert.equal(copy.apply(saved,'fear',10,1,101),false);copy.push(saved,20,{id:101});assert.equal(saved.p,p);});
test('immune and blocked fear attempts do not consume the displacement limit',()=>{const g=rich(),boss=enemy(g,'giant'),shadow=enemy(g,'shadow');g.apply(boss,'fear',1,1,99);assert.equal(boss.displacementCount,undefined);g.s.time=5;g.apply(shadow,'fear',1,1,99);g.push(shadow,20,{id:99});assert.equal(shadow.displacementCount,undefined);g.s.time=10;assert.ok(g.apply(shadow,'fear',1,1,99));assert.equal(shadow.displacementCount,1);});
test('swarm displacement counts once per area application and survives member deaths',()=>{const g=swarmGame(),members=g.s.enemies.slice();for(const e of members)g.apply(e,'fear',1,1,99);assert.ok(members.every(e=>e.displacementCount===1));const pushed=new Set();for(const e of members)g.push(e,20,{id:99},pushed);assert.ok(members.every(e=>e.displacementCount===2));g.kill(members[0]);g.s.time+=.1;g.apply(members[1],'fear',1,1,99);assert.ok(g.swarm(members[1]).every(e=>e.displacementCount===3));const p=members[1].p;g.push(members[1],20,{id:99});assert.equal(members[1].p,p);assert.equal(g.apply(members[1],'fear',10,1,100),false);assert.equal(new Set(g.swarm(members[1]).map(e=>e.p)).size,1);});
test('Skull Screecher has 240000 HP, appears at 80, rejects all effects and enemy buffs but takes damage',()=>{const g=rich();g.s.active=true;g.s.queue=[];const e=enemy(g,'screecher',220);assert.equal(e.hp,240000);assert.equal(D.enemies.screecher.wave,80);for(const wave of [45,55,79])assert.ok(!g.generateWave(wave).includes('screecher'));for(const kind of ['slow','stun','freeze','fear','push','poison','burn','weak','hunter','bounty','shield','haste'])assert.equal(g.apply(e,kind,20,1,99),false);g.push(e,50,{id:99});assert.equal(e.p,220);const hp=e.hp;g.hit(e,100);assert.equal(e.hp,hp-100);enemy(g,'shaman',220);enemy(g,'captain',220);e.wanderDirection=1;e.wanderUntil=100;const p=e.p;g.tick(.1);assert.equal(e.shield,0);assert.ok(Math.abs(e.p-p-e.speed*.1)<1e-8);assert.equal(e.effects.length,0);});
test('Screecher wanders for fifteen seconds, targets closest pair over strongest and reaches path edge without leaving path',()=>{const g=rich(),a=hero(g,'knight',[],550,390),b=hero(g,'archer',[],550,450),far=hero(g,'mage',[],190,230);for(const h of [a,b,far]){h.u=[0,0,0,0];h.clock=10000;}far.spent=100000;g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=10000;const e=enemy(g,'screecher',nearest(650,395).p);e.wanderDirection=0;e.wanderUntil=1000;g.tick(14.9);assert.equal(e.screechPhase,'wander');g.tick(.1);assert.deepEqual(new Set(e.screechTargets),new Set([a.id,b.id]));assert.ok(Math.abs(nearest(e.screechGoal.x,e.screechGoal.y).distance-26)<1e-7);const saved=new Game(g.save());let steps=0;while(!e.dead&&steps++<3000){g.tick(.02);saved.tick(.02);assert.ok(nearest(e.x,e.y).distance<=26.00001);}assert.ok(e.dead);assert.deepEqual(g.save(),saved.save());assert.ok(a.stunnedUntil>g.s.time);assert.ok(b.stunnedUntil>g.s.time);assert.equal(far.stunnedUntil,undefined);assert.equal(g.events.filter(ev=>ev.type==='skullScream').length,1);});
test('Screecher pause and early death prevent scream; missing heroes do not block resolution',()=>{const g=rich(),e=enemy(g,'screecher');g.s.active=false;g.tick(70);assert.equal(g.s.time,0);g.hit(e,240000);assert.ok(e.dead);assert.equal(g.events.filter(ev=>ev.type==='skullScream').length,0);const empty=rich();empty.s.active=true;empty.s.queue=[];const lone=enemy(empty,'screecher',200);lone.born=-15;for(let i=0;i<120;i++)empty.tick(.05);assert.ok(lone.dead);assert.equal(empty.s.active,false);});
test('Screecher naturally pauses and reverses, then replans if an approach target is sold',()=>{const g=rich();g.s.seed=1;g.s.active=true;g.s.queue=[];const e=enemy(g,'screecher',1000),states=new Set();for(let i=0;i<140;i++){g.tick(.1);states.add(e.wanderDirection);assert.ok(nearest(e.x,e.y).distance<1e-6);}assert.deepEqual([...states].sort(),[-1,0,1]);const a=hero(g,'knight',[0,0,0,0],550,390),b=hero(g,'archer',[0,0,0,0],550,450);a.clock=b.clock=10000;g.tick(1);g.sell(a.id);g.tick(.05);assert.deepEqual(e.screechTargets,[b.id]);for(let i=0;i<5000&&!e.dead;i++)g.tick(.02);assert.ok(e.dead);});
test('Knight shield stuns are reduced by 75 percent at every passive tier',()=>{for(const [tier,seconds] of [[1,.25],[4,.5],[5,.5]]){const g=rich(),h=hero(g,'knight',[0,0,tier,0]),e=enemy(g,'giant',220);e.blocks=0;h.count=2;h.bash=tier===5?2:0;g.attack(h);assert.equal(e.effects.find(f=>f.kind==='stun').end-g.s.time,seconds);}});
test('Knight primary stuns are heavily reduced without changing Mage stuns',()=>{for(const [path,seconds] of [[0,.625],[1,1.5625],[2,1.25]]){const g=rich(),u=[0,0,0,0];u[path]=6;const h=hero(g,'knight',u),e=enemy(g,'giant',220);e.blocks=0;g.s.active=true;assert.ok(g.cast(h.id));assert.equal(e.effects.find(f=>f.kind==='stun').end-g.s.time,seconds);}const g=rich(),h=hero(g,'mage',[0,0,4,0]),e=enemy(g,'giant',220);e.blocks=0;h.count=4;g.attack(h);assert.equal(e.effects.find(f=>f.kind==='stun').end-g.s.time,1);});
function throwScene(type='skeleton',p=300){const g=rich();g.s.active=true;g.s.queue=[];const w=g.spawn('werewolf',false,p),e=g.spawn(type,false,p+20);w.speed=0;for(const m of g.swarm(e))m.speed=0;return {g,w,e};}
test('Werewolf matches weaker Cyclops HP with half its speed, debuts at 60, picks up after five seconds and throws 2000 ahead',()=>{const {g,w,e}=throwScene();assert.equal(w.hp,D.enemies.brute.hp);assert.equal(D.enemies.werewolf.time,D.enemies.brute.time*2);assert.equal(D.enemies.werewolf.wave,60);assert.ok(!g.generateWave(59).includes('werewolf'));g.tick(4.99);assert.equal(g.s.enemyThrows.length,0);g.tick(.01);assert.equal(g.s.enemyThrows.length,1);const start=e.p;g.tick(.4);assert.ok(e.y<position(e.p).y);assert.equal(g.s.enemyThrows.length,1);g.tick(.4);assert.equal(g.s.enemyThrows[0].released,true);g.tick(1.61);assert.equal(e.p,Math.min(length-1,start+2000));assert.equal(e.throwId,undefined);assert.equal(g.s.enemyThrows.length,0);assert.equal(nearest(e.x,e.y).distance,0);});
test('Werewolf swarm throws preserve individuals and saved trajectory, allow damage, and pause',()=>{const {g,w,e}=throwScene('tiny');g.tick(5);g.tick(.8);assert.equal(g.s.enemyThrows[0].members.length,10);g.hit(e,100);const copy=new Game(g.save());for(let i=0;i<170;i++){g.tick(.02);copy.tick(.02);}assert.deepEqual(g.save(),copy.save());const remaining=g.s.enemies.filter(e=>e.type==='tiny');assert.equal(remaining.length,9);assert.ok(remaining.every(e=>e.p===Math.min(length-1,2320)&&!e.throwId));g.s.active=false;const before=g.save();g.tick(20);assert.deepEqual(g.save(),before);});
test('Werewolf interrupted pickup drops enemies, but released throws survive carrier death',()=>{for(const released of [false,true]){const {g,w,e}=throwScene();g.tick(5);if(released)g.tick(.8);g.hit(w,9999);g.tick(4);assert.equal(e.p,released?Math.min(length-1,2320):320);assert.equal(e.throwId,undefined);assert.equal(g.s.enemyThrows.length,0);}const {g,w,e}=throwScene();g.tick(5);g.apply(w,'stun',3,1,99);g.tick(.1);assert.equal(e.p,320);assert.equal(e.throwId,undefined);});
test('Werewolf skips immune allies and other carriers, caps landing before exit, and cleans up dead cargo',()=>{const {g,w,e}=throwScene('screecher');g.tick(5);assert.equal(g.s.enemyThrows.length,0);const shadow=g.spawn('shadow',false,w.p);shadow.born=g.s.time-5;w.nextThrowAt=g.s.time;g.startWerewolfThrows();assert.equal(g.s.enemyThrows.length,0);const near=throwScene('skeleton',length-100);near.g.tick(5);assert.equal(near.g.s.enemyThrows[0].goal,length-1);near.g.hit(near.e,999);near.g.tick(.1);assert.equal(near.g.s.enemyThrows.length,0);assert.equal(near.w.throwBusy,undefined);});
test('Werewolf is actually slower, stops for the windup and lifts cargo overhead then behind its back',()=>{const g=rich();g.s.active=true;g.s.queue=[];const w=g.spawn('werewolf',false,300),brute=g.spawn('brute',false,1500);const start=w.p;g.tick(1);assert.ok(Math.abs((w.p-start)*2-(brute.p-1500))<1e-7);const e=g.spawn('skeleton',false,w.p+20);e.speed=0;w.nextThrowAt=g.s.time;g.tick(.01);const planted=w.p;g.tick(.375);assert.equal(w.throwStage,'overhead');assert.ok(e.y<w.y-135);g.tick(.1875);assert.equal(w.throwStage,'behind back');assert.ok((e.x-w.x)*(w.throwFacing||1)>30);g.tick(.20);assert.ok(g.s.enemyThrows[0].released);assert.equal(w.p,planted);assert.equal(g.s.enemyThrows[0].goal-g.s.enemyThrows[0].start,2000);});
test('Werewolf throw has no stationary hand holds and resumes walking after follow-through',()=>{const {g,w}=throwScene();for(let i=1;i<=100;i++){const a=g.werewolfGrip((i-1)/100),b=g.werewolfGrip(i/100);assert.ok(Math.hypot(b.x-a.x,b.y-a.y)>0);assert.ok(Math.hypot(b.x-a.x,b.y-a.y)<5);}w.speed=20;w.nextThrowAt=0;g.tick(.01);const p=w.p;g.tick(.75);assert.equal(w.p,p);g.tick(.5);assert.equal(w.p,p);assert.ok(w.throwGrip);assert.ok(w.throwRecovery>.49);g.tick(.51);assert.ok(w.p>p);assert.equal(w.throwGrip,undefined);assert.ok(w.throwBusy);assert.equal(g.s.enemyThrows.length,1);});
test('Werewolf low arc has forty units of extra midpoint height and saves recovery progress',()=>{const {g,w,e}=throwScene();g.tick(5);g.tick(.75);const t=g.s.enemyThrows[0],landing=position(t.goal);g.tick(.8);assert.ok(Math.abs(e.y-((t.throwY+landing.y)/2-40))<1e-7);assert.ok(Math.abs(w.throwRecovery-.8)<1e-7);const copy=new Game(g.save());g.tick(.1);copy.tick(.1);assert.deepEqual(g.save(),copy.save());});
test('Rogue gold nerf carries fractional bonus coins across kills and saves',()=>{const g=rich(),h=hero(g,'rogue',[0,0,0,1]);const before=g.s.money;g.kill(enemy(g,'tiny'),h);assert.equal(g.s.money-before,2);const copy=new Game(g.save());for(let i=0;i<4;i++){g.kill(enemy(g,'tiny'),h);copy.kill(enemy(copy,'tiny'),copy.s.heroes[0]);}assert.equal(g.s.money-before,11);assert.equal(g.s.money,copy.s.money);assert.equal(g.s.bonusGoldRemainder,copy.s.bonusGoldRemainder);});
test('Leader passive and both money abilities give the reduced rewards without stacking',()=>{for(const type of ['rogue','leader']){const g=rich(),h=hero(g,type,[0,0,0,6]);g.s.active=true;assert.ok(g.cast(h.id));const before=g.s.money;const e=enemy(g,'screecher',190);g.kill(e);const passive=.05;assert.equal(g.s.money-before,Math.floor(D.enemies.screecher.reward*(1+passive)*1.625));}});
test('Leader wave gold remains 15 at every population',()=>{for(const low of [false,true]){const g=rich();hero(g,'leader',[0,0,0,4]);g.s.active=true;g.s.queue=[];g.s.villagers=low?50:100;const before=g.s.money;g.tick(.01);assert.equal(g.s.money-before,35);}});
test('Enemies share a lifetime cap of twelve slows freezes and stuns; the last effect is not refreshed',()=>{const g=rich(),e=enemy(g,'brute');for(let i=0;i<12;i++){g.s.time=i;assert.equal(g.apply(e,['slow','freeze','stun'][i%3],3,.3,99),true);}assert.equal(e.slowCount,12);const effects=JSON.stringify(e.effects);g.s.time=12;for(const kind of ['slow','freeze','stun'])assert.equal(g.apply(e,kind,100,1,100),false);assert.equal(JSON.stringify(e.effects),effects);const saved=new Game(g.save()),copy=saved.s.enemies[0];assert.equal(copy.slowCount,12);assert.equal(saved.apply(copy,'slow',1,.2,99),false);});
test('Withering poison still damages and weakens armor after its slow allowance is exhausted',()=>{const g=rich(),e=enemy(g,'brute');for(let i=0;i<12;i++)assert.ok(g.apply(e,'poison',3,4,99,{wither:true}));assert.equal(e.slowCount,12);const end=e.effects.find(f=>f.kind==='slow').end;g.s.time=1;assert.ok(g.apply(e,'poison',6,8,99,{wither:true}));assert.equal(e.slowCount,12);assert.equal(e.effects.find(f=>f.kind==='slow').end,end);assert.equal(e.effects.find(f=>f.kind==='poison').end,7);});
test('Swarm area slows count once per member and immune or blocked attempts do not consume slow charges',()=>{const g=rich(),first=g.spawn('tiny',false,200),members=g.swarm(first);for(let i=0;i<12;i++){g.s.time=i;for(const member of members)g.apply(member,'slow',2,.3,99);}assert.ok(members.every(e=>e.slowCount===12));g.s.time=13;assert.equal(g.apply(first,'freeze',5,1,99),false);for(const type of ['screecher','nightmare','shadow','giant']){const e=g.spawn(type);if(type==='shadow')e.born=g.s.time-5;assert.equal(g.apply(e,'slow',2,.2,99),false);assert.equal(e.slowCount,undefined);}});
test('Non-boss health gains compound by fifteen percent after 45 and every twenty waves thereafter',()=>{const g=new Game();for(const [wave,steps] of [[1,0],[45,0],[46,1],[65,1],[66,2],[85,2],[86,3],[105,3],[106,4],[125,4],[126,5],[206,9]]){g.s.wave=wave;for(const type of Object.keys(D.enemies)){const e=g.spawn(type),base=D.enemies[type].hp*(1+Math.max(0,wave-100)*.05),factor=D.enemies[type].boss?1:Math.pow(1.15,steps);assert.ok(Math.abs(e.maxHp-base*factor)<1e-7,`${type} wave ${wave}`);assert.equal(e.hp,e.maxHp);}}});
test('Milestone buff migrates active saves once while preserving missing-health percentage and bosses',()=>{const g=new Game();g.s.wave=86;g.s.active=true;for(const type of ['skeleton','giant','dragon'])g.spawn(type);const old=g.save();delete old.enemyMilestoneVersion;for(const e of old.enemies){e.maxHp=D.enemies[e.type].hp;e.hp=e.maxHp*.4;}const copy=new Game(old);for(const e of copy.s.enemies){assert.equal(e.maxHp,D.enemies[e.type].hp*copy.enemyMilestoneHealth(e.type));assert.ok(Math.abs(e.hp/e.maxHp-.4)<1e-10);}assert.deepEqual(new Game(copy.save()).save(),copy.save());});
test('Weaker Cyclops receives milestone buffs and version-one saves correct it once',()=>{const g=new Game();g.s.wave=86;g.s.active=true;const cyclops=g.spawn('giant'),wyvern=g.spawn('dragon'),skeleton=g.spawn('skeleton');assert.equal(cyclops.maxHp,13500*Math.pow(1.15,3));assert.equal(wyvern.maxHp,84825);const old=g.save();old.enemyMilestoneVersion=1;old.enemies[0].maxHp=13500;old.enemies[0].hp=6750;const fixed=new Game(old);assert.equal(fixed.s.enemies[0].maxHp,cyclops.maxHp);assert.equal(fixed.s.enemies[0].hp,cyclops.maxHp*.5);assert.equal(fixed.s.enemies[1].maxHp,wyvern.maxHp);assert.equal(fixed.s.enemies[2].maxHp,skeleton.maxHp);assert.deepEqual(new Game(fixed.save()).save(),fixed.save());});
test('Fire-only Wraith blocks weapons, poison and non-fire spells before shield damage, but takes fire',()=>{const g=rich(),e=enemy(g,'shaman');e.shield=40;const hp=e.hp;for(const type of ['physical','poison','ice','lightning','arcane'])g.hit(e,999,null,999,false,type);assert.equal(e.hp,hp);assert.equal(e.shield,40);assert.equal(g.apply(e,'poison',5,10,99,{wither:true}),false);g.hit(e,50,null,999,false,'fire');assert.equal(e.hp,hp-10);assert.equal(e.shield,0);assert.ok(g.apply(e,'burn',3,4,99));});
test('Fire Mage fireballs and ground fire respect fire-only and fire-immune traits',()=>{for(const type of ['shaman','hellhound']){const g=rich(),h=hero(g,'mage',[1,0,0,0]),e=enemy(g,type,220);e.speed=0;const before=e.hp;g.attack(h);assert.equal(e.hp<before,type==='shaman');const after=e.hp;g.s.active=true;g.s.queue=[];h.clock=1000;g.zone(h,'fire',e,85,4,10);g.tick(.1);assert.equal(e.hp<after,type==='shaman');assert.equal(g.apply(e,'burn',3,4,h.id),type==='shaman');}});
test('Meteors damage Wraiths but not Hell Hounds, while physical blast chains still work',()=>{for(const type of ['shaman','hellhound']){const g=rich(),h=hero(g,'mage',[6,0,0,0]),e=enemy(g,type,220);e.speed=0;h.clock=1000;g.s.active=true;g.s.queue=[];const hp=e.hp;g.zone(h,'meteor',e,85,8,100);g.tick(.51);assert.equal(e.hp<hp,type==='shaman');}const g=rich(),h=enemy(g,'hellhound'),w=enemy(g,'shaman');g.hit(h,1000);assert.equal(w.hp,w.maxHp);});
test('Headless Zombie poison immunity preserves physical damage and descriptions advertise every trait',()=>{const g=rich(),e=enemy(g,'headless'),hp=e.hp;assert.equal(g.apply(e,'poison',10,20,99,{wither:true}),false);assert.equal(e.effects.length,0);g.hit(e,100,null,999,true,'poison');assert.equal(e.hp,hp);g.hit(e,10);assert.equal(e.hp,hp-10);assert.match(D.enemies.headless.hint,/POISON IMMUNE/);assert.match(D.enemies.hellhound.hint,/FIRE IMMUNE/);assert.match(D.enemies.shaman.hint,/FIRE ONLY/);});
test('Mixed Fire and Arcane Mage paths do not turn arcane beams into fire damage',()=>{const g=rich(),h=hero(g,'mage',[1,0,0,3]),e=enemy(g,'shaman',220);h.count=2;const hp=e.hp;g.attack(h);assert.equal(e.hp,hp);h.count=0;g.attack(h);assert.ok(e.hp<hp);});
test('Plague Wyvern and Zombie Guard reject poison without consuming effect blocks',()=>{for(const type of ['dragon','shield']){const g=rich(),e=enemy(g,type),hp=e.hp,blocks=e.blocks;assert.equal(g.apply(e,'poison',5,100,99,{wither:true}),false);g.hit(e,100,null,999,true,'poison');assert.equal(e.hp,hp);assert.equal(e.blocks,blocks);assert.equal(e.effects.length,0);g.hit(e,10,null,999);assert.equal(e.hp,hp-10);assert.match(D.enemies[type].hint,/POISON IMMUNE/);}});
test('Fusion resists knockback but its spawned swarms can still be pushed',()=>{const g=rich(),e=enemy(g,'fusion',500);g.push(e,80,{id:99});assert.equal(e.p,500);assert.equal(e.displacementCount,undefined);assert.ok(g.apply(e,'slow',2,.2,99));g.s.active=true;g.s.queue=[];g.kill(e);g.tick(1.21);const child=g.s.enemies.find(e=>e.type==='tiny'),p=child.p;g.push(child,80,{id:99});assert.equal(child.p,p-80);assert.match(D.enemies.fusion.hint,/KNOCKBACK IMMUNE/);});
test('Werewolf rejects fear while retaining stun and freeze counters',()=>{const g=rich(),e=enemy(g,'werewolf');assert.equal(g.apply(e,'fear',10,1,99),false);assert.equal(e.displacementCount,undefined);for(const kind of ['stun','freeze'])assert.ok(g.apply(e,kind,2,1,99));assert.match(D.enemies.werewolf.hint,/FEAR IMMUNE/);});
test('Vampire Lord takes fifty percent extra fire from hits and burn ticks, not physical damage',()=>{const g=rich(),e=enemy(g,'captain'),hp=e.hp;e.speed=0;g.hit(e,20,null,0,false,'fire');assert.equal(e.hp,hp-30);g.hit(e,20);assert.equal(e.hp,hp-50);g.s.active=true;g.s.queue=[];g.apply(e,'burn',4,10,99);g.tick(1);assert.equal(e.hp,hp-65);assert.match(D.enemies.captain.hint,/50% more damage/);});
test('Loading saves removes newly immune statuses while preserving allowed effects',()=>{const g=rich();for(const type of ['shield','dragon','werewolf','fusion']){const e=enemy(g,type);e.effects=[{kind:type==='werewolf'?'fear':type==='fusion'?'push':'poison',owner:99,end:20,value:1},{kind:'burn',owner:99,end:20,value:1}];}const restored=new Game(g.save());for(const e of restored.s.enemies)assert.deepEqual(e.effects.map(f=>f.kind),['burn']);});


test('No map restores villagers at round milestones',()=>{for(const map of ['forest','marsh','volcano'])for(const wave of [1,29,30,31,59,60,90,120,150]){const g=new Game(null,map);g.s.wave=wave;g.s.active=true;g.s.queue=[];g.s.villagers=80;g.tick(.01);const bonus=0;assert.equal(g.s.villagers,80+bonus,map+' '+wave);assert.equal(g.events.find(e=>e.type==='complete').restoredLives,bonus);g.tick(1);assert.equal(g.s.villagers,80+bonus);const saved=new Game(g.save());saved.tick(1);assert.equal(saved.s.villagers,80+bonus,'reload must not duplicate reward');}});
test('Marsh milestone life reward waits for victory and does not revive a lost game',()=>{const g=new Game(null,'marsh');g.s.wave=30;g.s.active=true;g.s.queue=[];g.s.villagers=1;const e=g.spawn('skeleton',false,g.length-1);e.speed=100;const saved=new Game(g.save());saved.tick(.001);assert.equal(saved.s.villagers,1,'unfinished wave gets no reward');saved.tick(1);assert.equal(saved.s.lost,true);assert.equal(saved.s.villagers,0);assert.equal(saved.events.some(e=>e.type==='complete'),false);});

test('New enemy introduction rounds restore ten villagers on every map only once',()=>{for(const map of ['forest','marsh','volcano']){const g=new Game(null,map);g.s.villagers=70;g.s.nextWave=['skeleton','runner'];assert.ok(g.startWave());assert.equal(g.s.villagers,70);const saved=new Game(g.save());saved.s.queue=[];saved.tick(.01);assert.equal(saved.s.villagers,80);assert.equal(saved.events.find(e=>e.type==='complete').restoredLives,10);saved.tick(1);assert.equal(saved.s.villagers,80);saved.s.nextWave=['skeleton','runner'];saved.startWave();saved.s.queue=[];saved.tick(.01);assert.equal(saved.s.villagers,80);saved.s.nextWave=['brute'];saved.startWave();saved.s.queue=[];saved.tick(.01);assert.equal(saved.s.villagers,90);}});
test('Introduction reward caps at 101, never reduces old populations, and is lost on defeat',()=>{for(const [before,after] of [[95,101],[100,101],[101,101],[120,120]]){const g=new Game();g.s.villagers=before;g.startWave();g.s.queue=[];g.tick(.01);assert.equal(g.s.villagers,after);}const g=new Game();g.s.villagers=1;g.startWave();g.s.queue=[];const e=g.spawn('skeleton',false,g.length-1);e.speed=100;g.tick(1);assert.equal(g.s.villagers,0);assert.ok(g.s.lost);});
test('A newly spawned enemy type also marks its round for a single introduction reward',()=>{const g=new Game();g.s.seen=['skeleton'];g.s.nextWave=['skeleton'];g.s.villagers=80;g.startWave();g.s.queue=[];const e=g.spawn('runner');assert.equal(g.s.introductionRewardPending,true);g.kill(e);g.tick(.01);assert.equal(g.s.villagers,90);assert.ok(g.s.seen.includes('runner'));});

test('Ordinary round income remains full at low population on every map',()=>{for(const map of ['forest','marsh','volcano'])for(const population of [1,50,100]){const g=new Game(null,map);g.s.villagers=population;g.s.active=true;g.s.queue=[];const before=g.s.money;g.tick(.01);assert.equal(g.s.money-before,20);}});

test('Plague Wyvern has 35 percent less HP and old saved bosses migrate exactly once',()=>{for(const wave of [100,120]){const g=new Game();g.s.wave=wave;const boss=g.spawn('dragon'),other=g.spawn('giant');assert.equal(boss.maxHp,84825*(1+Math.max(0,wave-100)*.05));const saved=g.save();delete saved.wyvernHealthVersion;saved.enemies[0].maxHp=130500*(1+Math.max(0,wave-100)*.05);saved.enemies[0].hp=saved.enemies[0].maxHp*.4;const updated=new Game(saved),e=updated.s.enemies[0];assert.equal(e.maxHp,boss.maxHp);assert.equal(e.hp,e.maxHp*.4);assert.equal(e.speed,boss.speed);assert.equal(e.blocks,15);assert.equal(updated.s.enemies[1].maxHp,other.maxHp);assert.deepEqual(new Game(updated.save()).save(),updated.save());}});

test('Older saves regenerate the new Headless debut without changing an active queue',()=>{const g=rich();g.s.wave=29;g.s.nextWave=['skeleton'];delete g.s.headlessWaveVersion;assert.ok(new Game(g.save()).s.nextWave.includes('headless'));g.s.active=true;g.s.queue=['skeleton'];assert.deepEqual(new Game(g.save()).s.queue,['skeleton']);});
