const {test}=require('node:test');const assert=require('node:assert/strict');const {Game}=require('../engine.js');const D=require('../data.js');
function setup(type='knight',u=[0,0,0,0]){const g=new Game();g.s.money=1e6;g.s.trees=[];const water=['serpent','pirate','turtle','waterbeast'].includes(type),h=g.addHero(type,water?460:190,water?640:230);h.x=190;h.y=230;h.u=u;h.clock=100;const e=g.spawn('ironling',false,230);e.hp=e.maxHp=1e6;e.speed=0;return{g,h,e};}
test('Ironling debuts on round 47 with two thirds Fusion health and identical speed',()=>{const g=new Game();assert.equal(D.enemies.ironling.hp,D.enemies.fusion.hp*2/3);assert.equal(D.enemies.ironling.time,D.enemies.fusion.time);for(let n=1;n<47;n++)assert.equal(g.generateWave(n).includes('ironling'),false);assert.ok(g.generateWave(47).includes('ironling'));g.s.wave=47;const a=g.spawn('ironling'),b=g.spawn('fusion');assert.ok(Math.abs(a.maxHp-b.maxHp*2/3)<1e-8);assert.equal(a.speed,b.speed);});
test('Every approved attack requires its own listed upgrade, including crosspaths and higher tiers',()=>{const rules=[['knight',2,1,'bash'],['knight',3,2,'fire'],['knight',0,4,'basic'],['archer',1,3,'trick'],['archer',2,1,'arrow'],['rogue',0,3,'vital'],['mage',3,2,'arcane'],['mage',0,1,'fire'],['serpent',3,2,'stream'],['toolmaker',3,5,'turret'],['pirate',2,1,'cannon'],['pirate',0,4,'ram'],['turtle',1,2,'slam'],['waterbeast',2,2,'slam'],['turtle',0,3,'fire']];for(const [type,path,tier,source]of rules){const {g,h,e}=setup(type);h.u[path]=tier-1;g.hit(e,10,h,0,false,source==='fire'?'fire':'physical',source);assert.equal(e.hp,e.maxHp,type+' below '+source);for(const n of [tier,6]){h.u[path]=n;const before=e.hp;g.hit(e,10,h,0,false,source==='fire'?'fire':'physical',source);assert.ok(e.hp<before,type+' '+source+' '+n);}}});
test('Unupgraded fire form damages Ironling but extinguished form and unqualified attacks do not',()=>{for(const type of Object.keys(D.heroes).concat('waterbeast')){const {g,h,e}=setup(type);g.attack(h);assert.equal(e.hp<e.maxHp,type==='abomination',type);}const {g,h,e}=setup('waterbeast',[0,0,2,0]);g.hit(e,20,h,0,false,'water');assert.equal(e.hp,e.maxHp);});
test('Shield Bash and Lingering Light do not unlock normal swords; control and qualified burns still work',()=>{let {g,h,e}=setup('knight',[0,0,1,0]);g.attack(h);g.attack(h);assert.equal(e.hp,e.maxHp);g.attack(h);assert.equal(e.maxHp-e.hp,15*1.25);assert.ok(e.effects.some(f=>f.kind==='stun'));({g,h,e}=setup('knight',[0,0,0,2]));g.attack(h);assert.equal(e.hp,e.maxHp);assert.ok(e.effects.some(f=>f.kind==='burn'));g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;g.tick(.5);assert.equal(e.maxHp-e.hp,3*1.25*.5);});
test('Trick Shot only damages with the extra arrows, while Flaming Tips upgrades normal arrows',()=>{let {g,h,e}=setup('archer',[0,3,0,0]);g.attack(h);g.attack(h);assert.equal(e.hp,e.maxHp);g.attack(h);assert.equal(e.maxHp-e.hp,3*18*1.25);({g,h,e}=setup('archer',[0,0,1,0]));g.attack(h);assert.equal(e.maxHp-e.hp,12*1.25);assert.ok(e.effects.some(f=>f.kind==='burn'));});
test('Vital Strike damages only critical dagger hits, not poison or crosspath bombs',()=>{const {g,h,e}=setup('rogue',[3,2,0,0]);g.attack(h);g.attack(h);assert.equal(e.hp,e.maxHp);assert.equal(e.effects.some(f=>f.kind==='poison'),false);g.attack(h);assert.equal(e.maxHp-e.hp,(18+10)*2*1.25);});
test('Cannon crosspath does not permit rocks, and ram qualification is separate',()=>{const {g,h,e}=setup('pirate',[0,2,1,0]);g.pirateAttack(h);assert.equal(e.hp,e.maxHp);g.pirateBroadside(h,1,80,45);assert.equal(e.maxHp-e.hp,100);const before=e.hp;g.pirateCharge(h,240,8,0);g.s.time=.7;g.updatePirates(.7);assert.equal(e.hp,before);});
test('Pressurized streams work but underwater drag and throws remain unable to damage',()=>{const {g,h,e}=setup('serpent',[0,2,0,2]);g.serpentBeam(h,32,5,18,0);assert.equal(e.maxHp-e.hp,40);const before=e.hp;g.hit(e,10000,h,999,false,'water');assert.equal(e.hp,before);});
test('Both Heavy Landing slams work while bites and shell attacks do not inherit permission',()=>{let {g,h,e}=setup('turtle',[0,2,0,0]);g.attack(h);assert.equal(e.hp,e.maxHp);g.turtleSlam(h);g.s.time=1.1;g.updateTurtles(.1);assert.equal(e.maxHp-e.hp,125);({g,h,e}=setup('waterbeast',[0,0,2,0]));g.attack(h);assert.equal(e.hp,e.maxHp);g.startWaterAction(h,2);g.s.time=2.9;g.updateWaterBeasts(.1);assert.equal(e.maxHp-e.hp,750);});
test('Unqualified control effects work but damaging effects and damage cannot touch shields or health',()=>{const {g,h,e}=setup('mage',[0,2,0,0]);e.shield=40;g.hit(e,500,h);assert.equal(e.shield,40);assert.equal(e.hp,e.maxHp);assert.equal(g.apply(e,'poison',3,10,h.id),false);assert.equal(g.apply(e,'burn',3,10,h.id),false);for(const kind of ['slow','stun','fear'])assert.ok(g.apply(e,kind,1,.2,h.id));const p=e.p;g.push(e,10,h);assert.equal(e.p,p-10);assert.equal(new Game(g.save()).s.enemies[0].hp,e.maxHp);});
test('Hell Hound explosions still hurt Ironling because they are enemy damage',()=>{const {g,e}=setup();const hound=g.spawn('hellhound',false,230);g.kill(hound);assert.equal(e.maxHp-e.hp,225);});

test('Blast Bolts turret damage cannot leak into the Tool Maker hammer',()=>{const {g,h,e}=setup('toolmaker',[2,0,0,5]);g.toolMelee(h,100,4);assert.equal(e.hp,e.maxHp);g.updateWorkshop(.01);assert.ok(e.hp<e.maxHp);});
test('Armor Breaker does not make lightning damage eligible; Fireball damages Ironling without it',()=>{let {g,h,e}=setup('mage',[0,0,2,2]);g.attack(h);assert.equal(e.maxHp-e.hp,15*1.25);const before=e.hp;g.hit(e,100,h,0,false,'physical','lightning');assert.equal(e.hp,before);({g,h,e}=setup('mage',[1,0,0,0]));g.attack(h);assert.equal(e.maxHp-e.hp,15*1.25);});

test('Withering Poison retains its non-damaging slow without applying poison damage',()=>{const {g,h,e}=setup('rogue',[0,5,0,0]);assert.equal(g.apply(e,'poison',3,10,h.id,{wither:true}),false);assert.ok(e.effects.some(f=>f.kind==='slow'));assert.equal(e.effects.some(f=>f.kind==='poison'),false);});
