const {test}=require('node:test');const assert=require('node:assert/strict');const {Game}=require('../engine.js');const D=require('../data.js');
function setup(u=[0,0,0,0]){const g=new Game();g.s.trees=[];g.s.money=100000;g.map={...g.map,water:[[[160,200],[220,200],[220,260],[160,260]]]};const h=g.addHero('pirate',190,230);assert.ok(h);h.u=u;h.clock=100;h.pirateRamAt=h.pirateCannonAt=h.pirateHatAt=100;g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;return{g,h};}
function enemy(g,type='brute',p=220){const e=g.spawn(type,false,p);e.speed=0;return e;}
test('Pirate requires water and uses a buffed physical rock as its base attack',()=>{const {g,h}=setup();assert.equal(g.addHero('pirate',500,300),null);const e=enemy(g);assert.ok(g.attack(h));assert.equal(e.maxHp-e.hp,17.5);assert.equal(g.range(h),220);});
test('Sharpened rocks pierce multiple enemies while respecting fire-only immunity',()=>{const {g,h}=setup([0,6,0,0]);const a=enemy(g,'giant'),b=enemy(g,'brute'),w=enemy(g,'shaman');g.attack(h);assert.ok(a.hp<a.maxHp&&b.hp<b.maxHp);assert.equal(w.hp,w.maxHp);assert.equal(g.range(h),260);});
test('Boat charge hits a capped crowd, returns home and cancels on stun',()=>{const {g,h}=setup([1,0,0,0]);for(let i=0;i<5;i++)enemy(g);assert.ok(g.pirateCharge(h,45,3,0));g.tick(.5);assert.equal(g.s.enemies.filter(e=>e.hp<e.maxHp).length,3);assert.equal(h.x,190);g.tick(.5);assert.equal(h.pirateRam,undefined);g.pirateCharge(h,45,3,0);h.stunnedUntil=10;g.tick(.1);assert.equal(h.pirateRam,undefined);});
test('Cannon damage is fire: it hits Wraiths but not Hell Hounds or hidden Shadows',()=>{const {g,h}=setup([0,0,1,0]),w=enemy(g,'shaman'),hound=enemy(g,'hellhound'),shadow=enemy(g,'shadow');g.s.time=5.5;g.pirateBroadside(h,1,80,45);assert.ok(w.hp<w.maxHp);assert.equal(hound.hp,hound.maxHp);assert.equal(shadow.hp,shadow.maxHp);});
test('Higher cannon tiers add cannons, damage and a longer reload',()=>{for(const tier of [1,3,6]){const {g,h}=setup([0,0,tier,0]);enemy(g,'giant');h.pirateCannonAt=0;g.tick(.01);assert.equal(h.pirateBalls.length,[0,1,1,2,2,3,4][tier]);assert.equal(h.pirateCannonAt,.01+[0,5,5.5,6,6.5,7,7.5][tier]);}});
test('Returning hat respects size, return gating and save state',()=>{const {g,h}=setup([0,0,0,1]),small=enemy(g,'runner'),big=enemy(g,'giant');big.blocks=0;assert.ok(g.launchPirateHat(h,10,5,.5,200));assert.equal(g.launchPirateHat(h,10,5,.5,200),false);g.tick(.8);assert.ok(small.effects.some(f=>f.kind==='stun'));assert.equal(big.effects.length,0);const copy=new Game(g.save()),ch=copy.s.heroes[0];assert.ok(ch.pirateHat);copy.tick(.81);assert.equal(ch.pirateHat,undefined);});
test('High tier hat can stun giants but respects immunity, blocks and lifetime control cap',()=>{const {g,h}=setup([0,0,0,6]),giant=enemy(g,'giant'),immune=enemy(g,'screecher');giant.blocks=0;g.launchPirateHat(h,90,8,2,Infinity);g.tick(.8);assert.ok(giant.effects.some(f=>f.kind==='stun'));assert.equal(immune.effects.length,0);assert.equal(giant.slowCount,1);const blocked=enemy(g,'giant'),capped=enemy(g,'brute');capped.slowCount=12;delete h.pirateHat;g.launchPirateHat(h,10,8,2,Infinity);g.tick(.8);assert.equal(blocked.blocks,6);assert.equal(blocked.effects.length,0);assert.equal(capped.effects.length,0);assert.equal(capped.slowCount,12);});
test('Pirate hats pause during a hero stun; round end clears attacks',()=>{const {g,h}=setup([0,0,0,1]);const e=enemy(g);g.launchPirateHat(h,10,2,.5,200);const x=h.pirateHat.x;h.stunnedUntil=2;g.tick(.5);assert.equal(h.pirateHat.x,x);assert.equal(h.pirateHat.end,2.1);h.stunnedUntil=0;g.s.queue=[];g.kill(e);g.tick(.01);assert.equal(g.s.active,false);assert.equal(h.pirateHat,undefined);});
test('All four tier-six Pirate abilities activate and preserve 6/2 crosspath rules',()=>{for(let p=0;p<4;p++){const u=[0,0,0,0];u[p]=6;const {g,h}=setup(u);enemy(g,'giant');assert.ok(g.cast(h.id),D.heroes.pirate.paths[p].name);assert.ok(h.cooldown>0);assert.equal(g.cast(h.id),false);}});
