const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game}=require('../engine.js');
const D=require('../data.js');
function setup(u=[0,0,0,0]){const g=new Game();g.s.money=100000;g.s.trees=[];g.map={...g.map,water:[[[160,205],[220,205],[220,255],[160,255]]]};const h=g.addHero('serpent',190,230);assert.ok(h);h.u=u;g.s.active=true;g.s.queue=[];h.clock=100;h.serpentThrowAt=h.serpentDiveAt=h.gooseAt=100;return {g,h};}
function enemy(g,type,p=230){const e=g.spawn(type,false,p);e.speed=0;return e;}
test('Serpent placement uses actual water on both maps; land heroes cannot occupy water',()=>{for(const map of ['forest','marsh']){const g=new Game(undefined,map);g.s.money=10000;let found;for(let y=85;y<704&&!found;y+=5)for(let x=40;x<1020;x+=5)if(g.canPlace(x,y,'serpent')){found={x,y};break;}assert.ok(found,map);assert.equal(g.canPlace(found.x,found.y,'knight'),false);assert.ok(g.addHero('serpent',found.x,found.y));assert.equal(g.addHero('serpent',found.x,found.y),null);assert.equal(g.addHero('serpent',190,230),null);}});
test('Throw weight rises by tier and bosses can never be thrown',()=>{for(const [type,level] of [['skeleton',1],['shield',2],['brute',3],['captain',4],['giant',5]]){const {g,h}=setup([level-1,0,0,0]),e=enemy(g,type),target=enemy(g,'screecher',160);e.blocks=0;assert.equal(g.serpentThrow(h),false,type);h.u[0]=level;assert.ok(g.serpentThrow(h),type);assert.ok(e.serpentFlight);assert.equal(e.displacementCount,1);}const {g,h}=setup([6,0,0,0]);enemy(g,'dragon').blocks=0;enemy(g,'screecher',160);assert.equal(g.serpentThrow(h),false);});
test('Throw damages both enemies on landing and persists exactly across a save',()=>{const {g,h}=setup([2,0,0,0]),e=enemy(g,'shield'),target=enemy(g,'brute',160),hp=e.hp,tp=target.hp;assert.ok(g.serpentThrow(h));g.tick(.4);const copy=new Game(g.save());g.tick(.51);copy.tick(.51);assert.deepEqual(copy.save(),g.save());assert.equal(e.serpentFlight,undefined);assert.equal(e.p,160);assert.equal(e.hp,hp-72);assert.equal(target.hp,tp-75);});
test('Throws honor knockback cap, enemy blocks, and release cargo if owner is sold',()=>{const {g,h}=setup([6,0,0,0]),e=enemy(g,'giant'),target=enemy(g,'screecher',160);assert.equal(g.serpentThrow(h),false);assert.equal(e.blocks,6);assert.equal(e.displacementCount,undefined);e.blocks=0;e.displacementCount=3;assert.equal(g.serpentThrow(h),false);e.displacementCount=0;assert.ok(g.serpentThrow(h));g.tick(.3);g.sell(h.id);g.tick(.01);assert.equal(e.serpentFlight,undefined);assert.equal(e.hp,e.maxHp);assert.equal(target.hp,target.maxHp);});
test('Tiny swarms throw together and consume one knockback charge per member',()=>{const {g,h}=setup([1,0,0,0]),first=enemy(g,'tiny'),members=g.swarm(first);enemy(g,'brute',160);assert.ok(g.serpentThrow(h));assert.ok(members.every(e=>e.serpentFlight===first.serpentFlight&&e.displacementCount===1));});
test('Small enemies drown after two seconds; Wyvern resurfaces alive after two seconds',()=>{for(const type of ['skeleton','dragon']){const {g,h}=setup([0,5,0,0]),e=enemy(g,type);e.blocks=0;assert.ok(g.serpentDrag(h));g.tick(1.99);assert.ok(e.serpentDive);assert.equal(e.dead,false);g.tick(.02);assert.equal(e.serpentDive,undefined);assert.equal(e.dead,type==='skeleton');if(type==='dragon')assert.equal(e.hp,e.maxHp-500);}});
test('Dives respect shadow immunity, fire-only damage, boss blocks and the twelve-control cap',()=>{for(const type of ['shadow','shaman','screecher','dragon']){const {g,h}=setup([0,6,0,0]),e=enemy(g,type);if(type==='shadow')g.s.time=5;assert.equal(g.serpentDrag(h),false,type);assert.equal(e.serpentDive,undefined);}const {g,h}=setup([0,6,0,0]),e=enemy(g,'brute');e.slowCount=12;assert.equal(g.serpentDrag(h),false);});
test('Stunning the serpent cancels its dive without killing its captive',()=>{const {g,h}=setup([0,2,0,0]),e=enemy(g,'skeleton');assert.ok(g.serpentDrag(h));h.stunnedUntil=10;g.tick(.5);assert.equal(e.serpentDive,undefined);assert.equal(h.serpentDive,undefined);assert.equal(e.hp,e.maxHp);assert.equal(e.effects.length,0);});
test('Geese stop enemies, later alternate fear, and cannot bypass caps or immunity',()=>{for(const fear of [false,true]){const {g,h}=setup([0,0,5,0]),e=enemy(g,'brute');g.s.geese=[{owner:h.id,x:e.x,y:e.y,end:10,fear}];g.tick(.01);assert.ok(e.effects.some(f=>f.kind===(fear?'fear':'stun')));assert.equal(g.s.geese.length,0);}const {g,h}=setup([0,0,5,0]),e=enemy(g,'werewolf');g.s.geese=[{owner:h.id,x:e.x,y:e.y,end:10,fear:true}];g.tick(.01);assert.equal(e.effects.length,0);});
test('Water beam damages several enemies but respects Wraith immunity and knockback cap',()=>{const {g,h}=setup([0,0,0,5]);const list=['brute','brute','shaman'].map(t=>enemy(g,t,220));for(const e of list)e.displacementCount=3;assert.ok(g.attack(h));assert.ok(list.slice(0,2).every(e=>e.hp===e.maxHp-162.5&&e.p===220));assert.equal(list[2].hp,list[2].maxHp);});
test('All four abilities work, remain locked at tier five, and preserve the crosspath restriction',()=>{for(let p=0;p<4;p++){const u=[0,0,0,0];u[p]=5;const {g,h}=setup(u);assert.equal(g.ability(h),null);assert.ok(g.upgrade(h.id,p));const e=enemy(g,'giant');e.blocks=0;enemy(g,'skeleton',160);assert.ok(g.cast(h.id),D.heroes.serpent.paths[p].name);assert.ok(h.cooldown>0);const other=(p+1)%4;assert.ok(g.upgrade(h.id,other));assert.ok(g.upgrade(h.id,other));assert.equal(g.upgrade(h.id,other),false);}});
test('Passive resisted dives wait for their next interval and resisted abilities consume cooldown',()=>{const {g,h}=setup([0,6,0,0]),e=enemy(g,'dragon');h.serpentDiveAt=0;g.tick(.01);assert.equal(e.blocks,14);for(let i=0;i<30;i++)g.tick(.05);assert.equal(e.blocks,14);assert.ok(g.cast(h.id));assert.equal(e.blocks,13);assert.ok(h.cooldown>0);});
test('Pausing freezes a capture and wave completion waits for its resolution',()=>{const {g,h}=setup([0,2,0,0]),e=enemy(g,'skeleton');assert.ok(g.serpentDrag(h));g.s.active=false;g.tick(10);assert.ok(e.serpentDive);assert.equal(g.s.time,0);g.s.active=true;g.tick(1);assert.equal(g.s.active,true);g.tick(1.01);assert.equal(g.s.active,false);assert.equal(e.dead,true);});
test('Flood upgrade becomes main attack with no water shots between grabs, and later purchases switch it',()=>{const {g,h}=setup();const e=enemy(g,'dragon');e.blocks=0;assert.ok(g.upgrade(h.id,1));assert.equal(g.serpentMainPath(h),1);assert.ok(h.serpentLurk);assert.equal(g.attack(h),false);assert.equal(e.hp,e.maxHp);g.tick(.01);assert.ok(e.serpentDive);g.tick(2.01);const hp=e.hp;g.tick(.5);assert.equal(e.hp,hp);assert.ok(!g.effects.some(f=>f.type==='orb'||f.type==='waterShot'));assert.ok(g.upgrade(h.id,3));assert.equal(g.serpentMainPath(h),3);assert.ok(g.attack(h));assert.ok(e.hp<hp);assert.equal(new Game(g.save()).serpentMainPath(h),3);assert.ok(g.upgrade(h.id,1));assert.equal(g.serpentMainPath(h),1);assert.equal(g.attack(h),false);});
test('Older flood builds default to underwater attacks; another path can become the main attack',()=>{const {g,h}=setup([0,1,0,0]);assert.equal(g.serpentMainPath(h),1);assert.ok(g.upgrade(h.id,0));assert.equal(g.serpentMainPath(h),0);const restored=new Game(g.save()),saved=restored.s.heroes[0];assert.equal(restored.serpentMainPath(saved),0);assert.equal(restored.stats(saved).baseDamage,35);assert.equal(g.attack(h),false);});
test('Drag rests scale by enemy size after the fixed two-second capture and persist in saves',()=>{for(const [type,rest] of [['tiny',.5],['skeleton',1],['shield',2],['brute',3],['captain',4],['giant',6],['dragon',8]]){const {g,h}=setup([0,1,0,0]),e=enemy(g,type);e.blocks=0;assert.ok(g.serpentDrag(h));assert.equal(h.serpentDive.end,2);assert.equal(h.serpentDiveAt,2+rest);const saved=new Game(g.save());assert.equal(saved.s.heroes[0].serpentDiveAt,2+rest);g.tick(2.01);assert.equal(h.serpentDive,undefined);assert.equal(h.serpentDiveAt,2+rest);}});
test('Higher flood tiers shorten recovery and multi-grabs use the largest victim',()=>{const {g,h}=setup([0,4,0,0]),small=enemy(g,'skeleton'),boss=enemy(g,'dragon');boss.blocks=0;assert.equal(g.serpentDragRecovery(h,small),5/6);h.u[1]=5;assert.equal(g.serpentDragRecovery(h,small),4/6);assert.ok(g.serpentDrag(h,5,1.25,true));assert.equal(h.serpentDiveAt,2+8*4/6);});
test('Every crosspath can attack during the preferred path cooldown using its own interval',()=>{const keys=['serpentThrowAt','serpentDiveAt','gooseAt','serpentBeamAt'];for(let main=0;main<4;main++)for(let other=0;other<4;other++){if(main===other)continue;const u=[0,0,0,0];u[main]=5;u[other]=2;const {g,h}=setup(u);h.serpentMainPath=main;for(const key of keys)h[key]=100;h[keys[other]]=0;enemy(g,'shield',230);enemy(g,'giant',160).blocks=0;g.tick(.01);assert.ok(h[keys[other]]>.01,`${main} with ${other}`);assert.equal(h[keys[main]],100);if(other!==1)assert.ok(Math.abs(h[keys[other]]-(.01+(other===3?1:0)+g.stats({...h,serpentMainPath:other}).interval))<1e-9);const deadline=h[keys[other]],copy=new Game(g.save());assert.equal(copy.s.heroes[0][keys[other]],deadline);g.tick(.01);assert.equal(h[keys[other]],deadline);}});
test('Crosspath waits for a drag to finish, then fires beams during its size-based recovery',()=>{const {g,h}=setup([0,5,0,2]);h.serpentMainPath=1;h.serpentDiveAt=0;h.serpentBeamAt=0;const boss=enemy(g,'dragon');boss.blocks=0;g.tick(.01);const recovery=h.serpentDiveAt;assert.ok(h.serpentDive);assert.equal(h.serpentBeamAt,0);g.tick(1);assert.equal(h.serpentBeamAt,0);g.tick(1.01);assert.equal(h.serpentDive,undefined);assert.ok(h.serpentBeamAt>g.s.time);assert.equal(h.serpentDiveAt,recovery);assert.ok(boss.hp<boss.maxHp-500);});
test('Upgrading one path does not reset the other path recovery',()=>{const {g,h}=setup([0,1,0,0]);h.serpentDiveAt=20;assert.ok(g.upgrade(h.id,3));assert.equal(h.serpentDiveAt,20);assert.equal(h.serpentBeamAt,0);h.serpentBeamAt=9;assert.ok(g.upgrade(h.id,3));assert.equal(h.serpentDiveAt,20);assert.equal(h.serpentBeamAt,9);});
test('Water Jet fires five evenly spaced pulses across one second then waits three seconds',()=>{const {g,h}=setup([0,0,0,1]),e=enemy(g,'brute');assert.ok(g.attack(h));assert.equal(e.hp,e.maxHp-27.5);assert.equal(h.serpentBeamAt,4);g.tick(.19);assert.equal(e.hp,e.maxHp-27.5);g.tick(.01);assert.equal(e.hp,e.maxHp-55);const copy=new Game(g.save());for(let i=0;i<4;i++){g.tick(.2);copy.tick(.2);}assert.equal(e.hp,e.maxHp-137.5);assert.equal(h.serpentStream,undefined);assert.deepEqual(copy.save(),g.save());g.tick(2.9);assert.equal(e.hp,e.maxHp-137.5);g.tick(.11);assert.ok(e.hp<e.maxHp-137.5);});
test('Stream retargets survivors, stops without enemies and cancels when stunned',()=>{const {g,h}=setup([0,0,0,1]),first=enemy(g,'skeleton',230),second=enemy(g,'brute',160);first.hp=1;g.attack(h);assert.equal(first.dead,true);const hp=second.hp;g.tick(.2);assert.ok(second.hp<hp);h.stunnedUntil=10;const before=second.hp;g.tick(.2);assert.equal(h.serpentStream,undefined);assert.equal(second.hp,before);const solo=setup([0,0,0,1]);const e=enemy(solo.g,'skeleton');e.hp=1;solo.g.attack(solo.h);solo.g.tick(.2);assert.equal(solo.h.serpentStream,undefined);});
test('Crosspath waits until a stream ends and then uses the three-second recovery',()=>{const {g,h}=setup([0,2,0,1]);h.serpentMainPath=3;h.serpentBeamAt=0;h.serpentDiveAt=0;const e=enemy(g,'dragon');e.blocks=0;g.tick(.01);assert.ok(h.serpentStream);assert.equal(h.serpentDive,undefined);g.tick(.5);assert.equal(h.serpentDive,undefined);g.tick(.51);assert.equal(h.serpentStream,undefined);assert.ok(h.serpentDive);assert.equal(h.serpentBeamAt,4.01);});
