const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Game}=require('../engine.js');
const D=require('../data.js');
function setup(u=[0,0,0,0]){const g=new Game();g.s.trees=[];g.s.money=100000;const h=g.addHero('toolmaker',190,230);assert.ok(h);h.u=u;h.clock=100;h.toolTrapAt=h.toolBoulderAt=100;g.s.active=true;g.s.queue=[];return {g,h};}
function enemy(g,type='brute',p=220){const e=g.spawn(type,false,p);e.speed=0;e.blocks=0;return e;}
test('Tool Maker is a land-only hammer hero and all four paths have six complete upgrades',()=>{const {g,h}=setup();assert.equal(D.heroes.toolmaker.cost,140);assert.equal(g.range(h),90);assert.equal(g.stats(h).damage,16.875);assert.equal(g.addHero('toolmaker',460,640),null);for(const p of D.heroes.toolmaker.paths){assert.equal(p.names.length,6);assert.equal(p.costs.length,6);assert.ok(p.descriptions.every(Boolean));assert.ok(p.ability.tierDescriptions[2]);}});
test('Twelve nerfed weapons strike thirty-six enemies without one-shotting full-health skeletons',()=>{const {g,h}=setup([6,0,0,0]);for(let i=0;i<36;i++)enemy(g,'skeleton',220);assert.ok(g.attack(h));assert.equal(g.s.enemies.filter(e=>e.dead).length,0);assert.ok(g.s.enemies.every(e=>e.hp===e.maxHp-56.25));assert.equal(h.toolSwing.count,12);assert.equal(h.toolSwing.start,0);});
test('Double-rang strikes on outward and return legs with separate pierce limits',()=>{const {g,h}=setup([0,1,0,0]);const e=enemy(g);assert.ok(g.attack(h));assert.equal(g.workshop().rangs.length,1);g.tick(.7);assert.equal(e.hp,e.maxHp-22.5);g.tick(.35);g.tick(.35);assert.equal(e.hp,e.maxHp-45);assert.equal(g.workshop().rangs.length,0);});
test('Second double-rang upgrade throws two; each leg pierces only its purchased allowance',()=>{const {g,h}=setup([0,2,0,0]);for(let i=0;i<6;i++)enemy(g,'giant',220);g.attack(h);assert.equal(g.workshop().rangs.length,2);g.tick(.7);assert.ok(g.workshop().rangs.every(r=>r.out.length===3&&r.back.length===0));g.tick(.69);assert.ok(g.workshop().rangs.every(r=>r.back.length===3));});
test('Rang flights survive save/reload exactly and freeze when owner is stunned',()=>{const {g,h}=setup([0,3,0,0]);enemy(g,'giant');g.attack(h);g.tick(.3);const copy=new Game(g.save());g.tick(.4);copy.tick(.4);assert.deepEqual(copy.save(),g.save());const shot=g.workshop().rangs[0],x=shot.x;h.stunnedUntil=10;g.tick(.4);assert.equal(shot.x,x);});
test('Crafted traps retain distinct damage and crowd-control effects',()=>{for(const kind of ['jaw','oil','anvil','saw','shrapnel']){const {g,h}=setup([0,0,5,0]),e=enemy(g,'giant'),before=e.hp;g.workshop().traps.push({id:99,owner:h.id,kind,p:e.p,x:e.x,y:e.y,power:1,end:30});g.tick(.01);assert.ok(e.hp<before,kind);assert.equal(g.workshop().traps.length,0);if(kind==='jaw')assert.ok(e.effects.some(f=>f.kind==='stun'));if(kind==='oil')assert.ok(e.effects.some(f=>f.kind==='slow'));if(kind==='anvil')assert.equal(e.displacementCount,1);}});
test('Boulder trap releases a slow path-following boulder and obeys its damage budget',()=>{const {g,h}=setup([0,0,6,0]),e=enemy(g,'giant',220);g.workshop().traps.push({id:99,owner:h.id,kind:'boulder',p:220,...g.position(220),power:1,end:30});g.tick(.01);assert.equal(g.workshop().traps.length,0);assert.equal(g.workshop().boulders.length,1);const b=g.workshop().boulders[0];assert.equal(e.hp,e.maxHp-1500);assert.equal(b.budget,6000);const p=b.p;g.tick(.5);assert.ok(Math.abs(b.p-(p-32.5))<1e-8);const other=enemy(g,'giant',b.p-10);b.budget=100;g.tick(.1);assert.equal(other.hp,other.maxHp-100);assert.equal(g.workshop().boulders.length,0);});
test('Boulders expire and cannot damage fire-only Wraiths or hidden Shadows',()=>{const {g,h}=setup([0,0,6,0]);const e=enemy(g,'shaman');g.s.time=5;const shadow=enemy(g,'shadow');shadow.born=0;g.workshop().boulders.push({id:99,owner:h.id,p:240,...g.position(240),end:5.2,budget:10000,damage:1600,hit:[],rotation:0});g.tick(.1);assert.equal(e.hp,e.maxHp);assert.equal(shadow.hp,shadow.maxHp);g.tick(.11);assert.equal(g.workshop().boulders.length,0);});
test('Turret upgrades create eight stronger machines; stun stops them and selling removes everything',()=>{const {g,h}=setup([0,0,0,6]);const e=enemy(g,'giant');g.tick(.01);assert.equal(g.workshop().turrets.length,8);assert.ok(g.workshop().turrets.every(t=>t.level===6));assert.ok(e.hp<e.maxHp);h.stunnedUntil=10;const hp=e.hp;g.tick(1);assert.equal(e.hp,hp);g.sell(h.id);assert.ok(Object.values(g.workshop()).every(list=>list.length===0));});
test('Boulder construction has a long independent cooldown and tier-six abilities work',()=>{const {g,h}=setup([0,0,6,0]);h.toolBoulderAt=0;enemy(g,'giant');g.tick(.01);assert.equal(h.toolBoulderAt,30.01);const deadline=h.toolBoulderAt;g.tick(1);assert.equal(h.toolBoulderAt,deadline);for(let p=0;p<4;p++){const fixture=setup();fixture.h.u[p]=6;enemy(fixture.g,'giant');assert.ok(fixture.g.cast(fixture.h.id),D.heroes.toolmaker.paths[p].name);assert.ok(fixture.h.cooldown>0);}});
test('Every turret tier increases the workshop count on legal nearby land',()=>{for(const [level,count] of [[1,1],[2,2],[3,3],[4,4],[5,6],[6,8]]){const {g,h}=setup([0,0,0,level]);g.toolTurrets(h);const turrets=g.workshop().turrets;assert.equal(turrets.length,count);for(const t of turrets){assert.ok(g.canPlace(t.x,t.y));assert.ok(turrets.every(other=>other.id===t.id||Math.hypot(other.x-t.x,other.y-t.y)>=32));}const saved=new Game(g.save());saved.s.trees=[];saved.toolTurrets(saved.s.heroes[0]);assert.equal(saved.workshop().turrets.length,count);}});
test('Cannot launch another volley or Rebound Storm before any rang returns',()=>{const {g,h}=setup([0,6,0,0]);enemy(g,'giant');assert.ok(g.attack(h));const shots=g.workshop().rangs.map(r=>r.id);assert.equal(g.attack(h),false);assert.equal(g.cast(h.id),false);assert.equal(h.cooldown,0);assert.deepEqual(g.workshop().rangs.map(r=>r.id),shots);g.tick(1.2);assert.equal(g.attack(h),false);const saved=new Game(g.save()),savedHero=saved.s.heroes[0];assert.equal(saved.attack(savedHero),false);g.tick(.21);assert.equal(g.workshop().rangs.length,0);assert.ok(g.cast(h.id));assert.equal(g.workshop().rangs.length,6);assert.equal(g.attack(h),false);});
test('Return restriction is per blacksmith and does not stop purchased melee swings',()=>{const {g,h}=setup([1,2,0,0]);enemy(g,'giant');g.attack(h);const count=g.workshop().rangs.length;assert.ok(g.attack(h));assert.equal(g.workshop().rangs.length,count);const other=g.addHero('toolmaker',190,300);assert.ok(other);other.u=[0,2,0,0];assert.ok(g.launchRangs(other,2,24,3));assert.equal(g.workshop().rangs.filter(r=>r.owner===other.id).length,2);});
test('One returned rang unlocks a volley while another remains airborne, including after saving',()=>{const {g,h}=setup([0,2,0,0]);enemy(g,'giant');g.attack(h);const first=g.workshop().rangs[0],second=g.workshop().rangs[1];first.duration=.4;g.tick(.41);assert.equal(g.workshop().rangs.length,1);assert.equal(g.workshop().rangs[0].id,second.id);const copy=new Game(g.save()),saved=copy.s.heroes[0];assert.ok(copy.attack(saved));assert.equal(copy.workshop().rangs.length,3);assert.equal(copy.attack(saved),false);});
test('Double-rangs track a moving target around a bend instead of missing its old position',()=>{const {g,h}=setup([0,2,0,0]);const e=enemy(g,'giant',220);e.speed=180;g.attack(h);const original={x:e.x,y:e.y};for(let i=0;i<45;i++)g.tick(1/60);assert.ok(Math.hypot(e.x-original.x,e.y-original.y)>50);assert.ok(e.hp<e.maxHp);assert.ok(g.workshop().rangs.every(r=>r.out.includes(e.id)));});
test('A double-rang redirects toward a surviving enemy if its original target dies',()=>{const {g,h}=setup([0,1,0,0]);const first=enemy(g,'brute',240),second=enemy(g,'brute',210);g.attack(h);assert.equal(g.workshop().rangs[0].target,first.id);g.kill(first);g.tick(.7);assert.equal(g.workshop().rangs[0].target,second.id);assert.ok(second.hp<second.maxHp);});
test('Twin rangs take separate arcs and still both hit the same target',()=>{const {g,h}=setup([0,2,0,0]);const e=enemy(g,'giant');g.attack(h);const [a,b]=g.workshop().rangs;assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>=31);g.tick(.35);assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>=70);assert.notEqual(a.spin,b.spin);g.tick(.35);assert.ok(a.out.includes(e.id)&&b.out.includes(e.id));assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>=31);g.tick(.35);assert.ok(Math.hypot(a.x-b.x,a.y-b.y)>=70);});
test('Tool Maker damage nerf covers ranged device proxies and slower turret timing',()=>{const {g,h}=setup([0,0,0,6]),e=enemy(g,'giant');assert.equal(g.stats(h).interval,1.5);g.hit(e,100,h);assert.equal(e.hp,e.maxHp-93.75);g.hit(e,100,{...h,toolRanged:true});assert.equal(e.hp,e.maxHp-187.5);g.tick(.01);assert.ok(g.workshop().turrets.every(t=>Math.abs(t.next-.885)<1e-9));});
