const {test}=require('node:test');const assert=require('node:assert/strict');const {Game}=require('../engine.js');const D=require('../data.js');
function setup(u=[0,0,0,0]){const g=new Game();g.s.trees=[];g.s.money=100000;g.map={...g.map,water:[[[160,205],[220,205],[220,260],[160,260]]]};const h=g.addHero('turtle',190,230);assert.ok(h);h.u=u;h.clock=100;h.turtleSlamAt=h.turtleShellAt=100;g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=1000;return{g,h};}
function enemy(g,type='brute',p=220){const e=g.spawn(type,false,p);e.speed=0;return e;}
test('Turtle is water-only, bites in melee, and has 24 named upgrades',()=>{const {g,h}=setup();assert.equal(g.addHero('turtle',500,300),null);assert.equal(D.heroes.turtle.cost,130);const e=enemy(g);assert.ok(g.attack(h));assert.equal(e.hp,e.maxHp-25);e.x=500;assert.equal(g.attack(h),false);assert.equal(g.stats(h).interval,1.4);for(const p of D.heroes.turtle.paths){assert.equal(p.names.length,6);assert.equal(p.descriptions.length,6);}});
test('Blazing Jaws accelerates bites; fire begins at tier 3 and obeys immunity',()=>{const {g,h}=setup([2,0,0,0]);const w=enemy(g,'shaman');g.attack(h);assert.equal(w.hp,w.maxHp);h.u[0]=3;g.attack(h);assert.ok(w.hp<w.maxHp);assert.ok(w.effects.some(f=>f.kind==='burn'));const hound=enemy(g,'hellhound',240);g.attack(h);assert.equal(hound.hp,hound.maxHp);assert.equal(hound.effects.length,0);assert.equal(g.stats(h).interval,.65);});
test('Body slam hits a bounded crowd on the path, then returns to the water anchor',()=>{const {g,h}=setup([0,1,0,0]);for(let i=0;i<7;i++)enemy(g);assert.ok(g.turtleSlam(h));assert.equal(g.attack(h),false);g.tick(1);assert.equal(g.s.enemies.filter(e=>e.hp<e.maxHp).length,4);assert.deepEqual({x:h.x,y:h.y},{x:190,y:230});g.tick(1.11);assert.equal(h.turtleAction,undefined);});
test('Shell captures, collides on both legs, releases survivors and survives save/reload',()=>{const {g,h}=setup([0,0,1,0]);const captive=enemy(g,'shield',220),victim=enemy(g,'giant',245);assert.ok(g.turtleShell(h));g.tick(.6);assert.equal(captive.turtleHeld.owner,h.id);const hp=captive.hp;g.hit(captive,500);assert.equal(captive.hp,hp);const copy=new Game(g.save()),saved=copy.s.heroes[0];copy.tick(1);assert.ok(copy.s.enemies.find(e=>e.id===victim.id).hp<victim.maxHp);copy.tick(.81);const freed=copy.s.enemies.find(e=>e.id===captive.id);assert.ok(freed);assert.equal(freed.turtleHeld,undefined);assert.equal(freed.serpentFlight,undefined);assert.equal(freed.p,220);assert.ok(freed.hp<hp);assert.equal(saved.turtleAction,undefined);assert.ok(copy.s.enemies.find(e=>e.id===victim.id).hp<=victim.maxHp-112.5);});
test('Shell capture respects enemy immunity, control cap, blocks and size',()=>{const {g,h}=setup([0,0,6,0]);const immune=enemy(g,'screecher'),blocked=enemy(g,'giant'),capped=enemy(g,'brute'),boss=enemy(g,'dragon');capped.slowCount=12;g.turtleShell(h);g.tick(.6);for(const e of [immune,blocked,capped,boss])assert.equal(e.turtleHeld,undefined);assert.equal(blocked.blocks,6);});
test('A tiny swarm is captured together and safely released when Turtle is sold',()=>{const {g,h}=setup([0,0,1,0]);const first=enemy(g,'tiny');g.turtleShell(h);g.tick(.6);assert.equal(g.swarm(first).filter(e=>e.turtleHeld).length,10);g.sell(h.id);assert.equal(g.s.enemies.some(e=>e.turtleHeld||e.serpentFlight),false);assert.ok(g.s.enemies.every(e=>e.slowCount===1));});
test('Explosive shell sprays shards and enforces a one-second shell regrowth',()=>{const {g,h}=setup([0,0,4,0]);enemy(g,'giant');g.turtleShell(h);g.tick(1.6);assert.ok(h.turtleBurst);assert.equal(h.turtleBurst.shards,8);assert.equal(h.turtleAction,undefined);assert.equal(h.turtleRecoverUntil,2.6);assert.equal(g.attack(h),false);g.tick(.99);assert.equal(g.attack(h),false);g.tick(.02);assert.ok(g.attack(h));});
test('Submerged mode disables every attack and earns saved fractional gold only during active unstunned rounds',()=>{const {g,h}=setup([2,0,0,1]);const e=enemy(g);h.target='submerged';const money=g.s.money;g.tick(2);assert.equal(g.s.money,money);assert.equal(g.attack(h),false);assert.equal(g.turtleSlam(h),false);assert.equal(g.turtleShell(h),false);g.hit(e,100,h);assert.equal(e.hp,e.maxHp);const copy=new Game(g.save()),ch=copy.s.heroes[0];copy.tick(1);assert.equal(copy.s.money,money+1);ch.stunnedUntil=100;copy.tick(3);assert.equal(copy.s.money,money+1);ch.stunnedUntil=0;copy.s.active=false;copy.tick(10);assert.equal(copy.s.money,money+1);ch.target='first';assert.ok(copy.attack(ch));});
test('Submerging or stunning cancels a capture without losing its enemies',()=>{for(const mode of ['submerged','stun']){const {g,h}=setup([0,0,2,1]);const e=enemy(g,'shield');g.turtleShell(h);g.tick(.6);assert.ok(e.turtleHeld);if(mode==='submerged')h.target='submerged';else h.stunnedUntil=10;g.tick(.01);assert.equal(e.turtleHeld,undefined);assert.equal(h.turtleAction,undefined);assert.equal(e.hp,e.maxHp);}});
test('Turtle crosspaths alternate special attacks and have only tier-six primary abilities',()=>{const {g,h}=setup([0,2,2,0]);enemy(g,'giant');h.turtleSlamAt=h.turtleShellAt=0;g.tick(.01);assert.equal(h.turtleAction.kind,'shell');g.tick(2.5);g.tick(.01);assert.equal(h.turtleAction.kind,'slam');for(let p=0;p<4;p++){const f=setup();f.h.u[p]=5;assert.equal(f.g.ability(f.h),null);f.h.u[p]=6;enemy(f.g,'giant');assert.ok(f.g.cast(f.h.id),D.heroes.turtle.paths[p].name);assert.ok(f.h.cooldown>0);}});

test('A captured Shadow Goul escapes the shell when shadow immunity starts',()=>{const {g,h}=setup([0,0,2,0]);const e=enemy(g,'shadow');g.s.time=4;g.turtleShell(h);g.tick(.6);assert.ok(e.turtleHeld);const hp=e.hp;g.tick(.5);assert.equal(e.turtleHeld,undefined);assert.equal(h.turtleAction,undefined);assert.equal(e.hp,hp);});
