const {test}=require('node:test'),assert=require('node:assert/strict');const {Game}=require('../engine.js');const D=require('../data.js');
function setup(u=[0,0,0,0]){const g=new Game();g.s.trees=[];g.s.money=1e5;const h=g.addHero('abomination',460,640);assert.equal(h.type,'waterbeast');h.u=u;h.x=190;h.y=230;h.clock=100;h.waterNext=[100,100,100,100];g.s.active=true;g.s.queue=['skeleton'];g.s.spawnClock=100;return{g,h};}
function enemy(g,type='giant',p=230){const e=g.spawn(type,false,p);e.speed=0;e.hp=e.maxHp=1e6;return e;}
test('Water placement selects a saved variant with four renamed six-tier paths',()=>{const {g,h}=setup();assert.equal(new Game(g.save()).s.heroes[0].type,'waterbeast');assert.deepEqual(D.heroes.waterbeast.paths.map(p=>p.name),['Crashing Surge','Stormshake','Deepwater Ambush','Predator’s Glare']);assert.ok(D.heroes.waterbeast.paths.every(p=>p.names.length===6));assert.equal(Object.keys(D.heroes).includes('waterbeast'),false);const e=enemy(g);assert.ok(g.attack(h));assert.equal(e.maxHp-e.hp,35);e.p=450;Object.assign(e,g.position(e.p));assert.equal(g.attack(h),false);});
test('Only the fire form can occupy lava and gains 10 percent damage',()=>{const g=new Game(null,'volcano');g.s.money=1e5;g.s.trees=[];let spot;for(let x=50;x<980&&!spot;x+=15)for(let y=90;y<650;y+=15)if(g.inLava(x,y)&&g.canPlace(x,y,'abomination')){spot={x,y};break;}assert.ok(spot);assert.equal(g.canPlace(spot.x,spot.y,'knight'),false);const h=g.addHero('abomination',spot.x,spot.y);assert.equal(h.type,'abomination');assert.ok(h.lavaEmpowered);assert.equal(g.buffs(h).damage,1.375);});
test('Dash pierces out and back once each and forbids attacks during three-second recovery',()=>{const {g,h}=setup([1,0,0,0]);const e=enemy(g);assert.ok(g.startWaterAction(h,0));assert.equal(g.attack(h),false);for(let i=0;i<15;i++)g.tick(.1);assert.equal(e.maxHp-e.hp,175);assert.equal(h.waterAction,undefined);assert.equal(g.attack(h),false);g.tick(3.1);assert.ok(g.attack(h));});
test('Stormshake applies slow pulses without damage or overlapping attacks',()=>{const {g,h}=setup([0,2,0,0]);const e=enemy(g,'brute');g.startWaterAction(h,1);g.tick(.1);assert.equal(e.hp,e.maxHp);assert.equal(g.attack(h),false);assert.ok(e.effects.some(f=>f.kind==='slow'&&f.value===.3));assert.equal(g.startWaterAction(h,1),false);});
test('Dive targets the strongest, waits underwater, lands once and returns home',()=>{const {g,h}=setup([0,0,1,0]);const e=enemy(g);g.startWaterAction(h,2);g.tick(1);assert.equal(e.hp,e.maxHp);assert.equal(g.waterPosition(h).submerged,true);g.tick(1.9);assert.equal(e.maxHp-e.hp,500);g.tick(.8);assert.equal(h.waterAction,undefined);assert.deepEqual(g.waterPosition(h),{x:h.x,y:h.y});});
test('Glare ignores shadow, screecher and boss immunity without damage; global cap and grace period persist',()=>{for(const type of ['shadow','screecher','dragon']){const {g,h}=setup([0,0,0,1]);const e=enemy(g,type);e.speed=100;e.blocks=99;e.slowCount=12;g.startWaterAction(h,3);g.tick(2.01);const p=e.p;assert.equal(e.gazeCount,1);assert.equal(e.hp,e.maxHp);assert.equal(g.stopWithGaze(e,{id:99},2),false);g.tick(.5);assert.equal(e.p,p);g.s.time=e.gazeUntil+2.99;assert.equal(g.stopWithGaze(e,h,2),false);g.s.time=e.gazeUntil+3;assert.ok(g.stopWithGaze(e,{id:99},2));g.s.time=e.gazeUntil+3;assert.equal(g.stopWithGaze(e,h,2),false);assert.equal(new Game(g.save()).s.enemies[0].gazeCount,2);}});
test('Glare sharing keeps tiny swarms together and stun pauses action windup',()=>{const {g,h}=setup([0,0,0,1]);const e=g.spawn('tiny',false,230);assert.ok(g.stopWithGaze(e,h,3));assert.ok(g.swarm(e).every(m=>m.gazeCount===1));enemy(g);g.startWaterAction(h,3);h.stunnedUntil=10;g.tick(1);assert.equal(h.waterAction.end,3);assert.equal(g.gazeStopped(e),false);});
test('Water tier-six abilities work for all paths and respect exclusive actions',()=>{for(let p=0;p<4;p++){const {g,h}=setup();h.u[p]=6;enemy(g);assert.ok(g.cast(h.id));assert.ok(h.waterAction);assert.equal(g.cast(h.id),false);}});

test('Flooded paths accept the Abomination water form, retain spacing, and follow drying rules',()=>{const g=new Game();g.s.trees=[];g.s.money=100000;const serpent=g.addHero('serpent',460,640);serpent.u[1]=1;let spot;for(let p=0;p<g.length;p+=10){const at=g.position(p);if(!g.inWater(at.x,at.y)&&g.inFlood(at.x,at.y)&&g.canPlace(at.x,at.y,'abomination')){spot=at;break;}}assert.ok(spot);assert.equal(g.canPlace(spot.x,spot.y,'knight'),false);const h=g.addHero('abomination',spot.x,spot.y);assert.equal(h.type,'waterbeast');assert.equal(h.floodDependent,true);assert.equal(g.canPlace(spot.x,spot.y,'abomination'),false);const copy=new Game(g.save());assert.equal(copy.s.heroes.find(o=>o.id===h.id).type,'waterbeast');copy.sell(serpent.id);assert.equal(copy.s.heroes.some(o=>o.id===h.id),false);g.sell(h.id);serpent.u[1]=0;assert.equal(g.canPlace(spot.x,spot.y,'abomination'),false);});
